[workspace]
members = ["crates/*", "tests/integration", "xtask"]
resolver = "3"

[workspace.package]
version      = "0.1.0-alpha.2"
edition      = "2024"
rust-version = "1.85"
license      = "MIT OR Apache-2.0"
repository   = "https://github.com/vaibhavgupta9877/ruprizzle-orm"
homepage     = "https://vaibhavgupta9877.github.io/ruprizzle-orm"
authors      = ["Vaibhav Gupta"]

[workspace.dependencies]
# --- internal ---
ruprizzle-core    = { path = "crates/core",    version = "0.1.0-alpha.2" }
ruprizzle-dialect = { path = "crates/dialect", version = "0.1.0-alpha.2" }
ruprizzle-parser  = { path = "crates/parser",  version = "0.1.0-alpha.2" }
ruprizzle-codegen = { path = "crates/codegen", version = "0.1.0-alpha.2" }
ruprizzle-migrate = { path = "crates/migrate", version = "0.1.0-alpha.2" }
ruprizzle-macros  = { path = "crates/macros",  version = "0.1.0-alpha.2" }
ruprizzle         = { path = "crates/runtime", version = "0.1.0-alpha.2" }
ruprizzle-testkit = { path = "crates/testkit" }

# --- external ---
pest         = "2.8"
pest_derive  = "2.8"
sqlx         = { version = "0.8", default-features = false, features = ["runtime-tokio", "any", "postgres", "sqlite", "macros", "uuid", "chrono", "json", "rust_decimal"] }
chrono       = { version = "0.4", features = ["serde"] }
rust_decimal = { version = "1", default-features = false, features = ["serde"] }
thiserror    = "2"
miette       = "7"
serde        = { version = "1", features = ["derive"] }
serde_json   = "1"
proc-macro2  = "1"
quote        = "1"
syn          = { version = "2", features = ["full"] }
prettyplease = "0.2"
clap         = { version = "4", features = ["derive", "env"] }
tokio        = { version = "1", features = ["macros", "rt-multi-thread"] }
indexmap     = { version = "2", features = ["serde"] }
sha2         = "0.10"
uuid         = { version = "1", features = ["v4", "serde"] }
tempfile     = "3"
insta        = { version = "1", features = ["json"] }
dotenvy      = "0.15"
notify       = "7"
walkdir      = "2"
criterion    = "0.5"

[profile.dev]
# Codegen output and sqlx make debug builds heavy; this trims link time without
# hurting debuggability of our own crates.
debug = 1

[profile.test]
debug = 1
