//! Token emission helpers.

use std::collections::BTreeMap;

use proc_macro2::{Ident, Span, TokenStream};
use quote::{format_ident, quote};
use ruprizzle_core::ir::{EnumDef, Field, FieldKind, Model, Provider, ScalarType, Schema};
use ruprizzle_parser::naming;

/// Generate all source files for a schema.
///
/// Returns a map from file path (relative to the output directory) to file
/// contents. The caller is responsible for atomic, idempotent disk writes.
pub fn generate_all(schema: &Schema) -> BTreeMap<String, String> {
    let mut files = BTreeMap::new();

    files.insert("_generated.rs".to_owned(), generated_rs(schema));
    files.insert("enums.rs".to_owned(), enums_rs(schema));
    files.insert("mod.rs".to_owned(), mod_rs(schema));

    for model in schema.models.values() {
        let path = format!("{}.rs", safe_module_name(model.name.as_str()));
        files.insert(path, model_rs(schema, model));
    }

    files
}

/// Format a token stream with `prettyplease`.
pub fn format(tokens: TokenStream) -> String {
    let file = syn::parse2::<syn::File>(tokens).expect("generated tokens must be valid Rust");
    prettyplease::unparse(&file)
}

fn header() -> TokenStream {
    quote! {
        // @generated by ruprizzle — DO NOT EDIT.
        // Regenerate with: ruprizzle generate
        #![allow(clippy::all, clippy::pedantic, unused_imports)]
    }
}

fn generated_rs(schema: &Schema) -> String {
    let hash = schema.fingerprint();
    let version = env!("CARGO_PKG_VERSION");
    let header = header();
    let tokens = quote! {
        #header

        /// Schema hash, used to detect stale generated code.
        pub const SCHEMA_HASH: &str = #hash;

        /// ruprizzle version that generated this code.
        pub const RUPRIZZLE_VERSION: &str = #version;
    };
    format(tokens)
}

fn enums_rs(schema: &Schema) -> String {
    let is_postgres = matches!(schema.datasource.provider, Provider::Postgres);
    let enum_items: Vec<_> = schema
        .enums
        .values()
        .map(|e| emit_enum(e, is_postgres))
        .collect();
    let header = header();

    let tokens = quote! {
        #header

        use ::ruprizzle::serde::{Deserialize, Serialize};
        use ::ruprizzle::sqlx::Type;
        use ::ruprizzle::Value;

        #( #enum_items )*
    };
    format(tokens)
}

fn emit_enum(e: &EnumDef, is_postgres: bool) -> TokenStream {
    let name = format_ident!("{}", e.name.as_str());
    let docs = doc_attrs(e.docs.as_deref());
    let type_name = &e.db_name;

    let variants: Vec<_> = e
        .variants
        .values()
        .map(|v| {
            let var = format_ident!("{}", pascal(&v.name));
            let docs = doc_attrs(v.docs.as_deref());
            quote! {
                #docs
                #var,
            }
        })
        .collect();

    let all_variants: Vec<_> = e
        .variants
        .values()
        .map(|v| {
            let var = format_ident!("{}", pascal(&v.name));
            quote! { #name::#var }
        })
        .collect();

    let as_db_arms: Vec<_> = e
        .variants
        .values()
        .map(|v| {
            let var = format_ident!("{}", pascal(&v.name));
            let db = &v.db_name;
            quote! { Self::#var => #db, }
        })
        .collect();

    let from_db_arms: Vec<_> = e
        .variants
        .values()
        .map(|v| {
            let var = format_ident!("{}", pascal(&v.name));
            let db = &v.db_name;
            quote! { #db => Some(Self::#var), }
        })
        .collect();

    let sqlx_attrs = if is_postgres {
        quote! { #[sqlx(type_name = #type_name, rename_all = "SCREAMING_SNAKE_CASE")] }
    } else {
        quote! { #[sqlx(rename_all = "SCREAMING_SNAKE_CASE")] }
    };

    quote! {
        #docs
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Type, Serialize, Deserialize)]
        #sqlx_attrs
        #[serde(crate = "::ruprizzle::serde")]
        pub enum #name {
            #( #variants )*
        }

        impl #name {
            /// All variants in declaration order.
            pub const ALL: &'static [#name] = &[ #( #all_variants ),* ];

            /// The database string for this variant.
            #[must_use]
            pub const fn as_db_str(&self) -> &'static str {
                match self {
                    #( #as_db_arms )*
                }
            }

            /// Parse a database string into a variant.
            #[must_use]
            pub fn from_db_str(s: &str) -> Option<Self> {
                match s {
                    #( #from_db_arms )*
                    _ => None,
                }
            }
        }

        impl std::fmt::Display for #name {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                f.write_str(self.as_db_str())
            }
        }

        impl std::str::FromStr for #name {
            type Err = String;

            fn from_str(s: &str) -> Result<Self, Self::Err> {
                Self::from_db_str(s).ok_or_else(|| format!("unknown {0}: {1}", stringify!(#name), s))
            }
        }

        impl ::ruprizzle::Encodable for #name {
            fn to_value(&self) -> Value {
                Value::Str(self.as_db_str().into())
            }
        }
    }
}

fn mod_rs(schema: &Schema) -> String {
    let mods: Vec<_> = schema
        .models
        .values()
        .map(|m| {
            let module = format_ident!("{}", safe_module_name(m.name.as_str()));
            quote! { pub mod #module; }
        })
        .collect();

    let uses: Vec<_> = schema
        .models
        .values()
        .map(|m| {
            let module = format_ident!("{}", safe_module_name(m.name.as_str()));
            let model = format_ident!("{}", m.name.as_str());
            let insert = format_ident!("{}Insert", m.name.as_str());
            let update = format_ident!("{}Update", m.name.as_str());
            let repo = format_ident!("{}Repo", m.name.as_str());
            quote! {
                pub use self::#module::{
                    #insert, #model, #repo, #update,
                };
            }
        })
        .collect();

    let repo_methods: Vec<_> = schema
        .models
        .values()
        .map(|m| {
            let method = format_ident!("{}", naming::snake_case(m.name.as_str()));
            let repo = format_ident!("{}Repo", m.name.as_str());
            quote! {
                /// Entry point for this model's repository.
                pub fn #method(&self) -> #repo<'_> {
                    #repo::new(self)
                }
            }
        })
        .collect();

    let prelude_uses: Vec<_> = schema
        .models
        .values()
        .map(|m| {
            let model = format_ident!("{}", m.name.as_str());
            let insert = format_ident!("{}Insert", m.name.as_str());
            let update = format_ident!("{}Update", m.name.as_str());
            let repo = format_ident!("{}Repo", m.name.as_str());
            let module = format_ident!("{}", safe_module_name(m.name.as_str()));
            quote! { #model, #insert, #update, #repo, #module, }
        })
        .collect();

    let header = header();
    let tokens = quote! {
        #header

        pub mod _generated;
        pub mod enums;

        #( #mods )*

        pub use _generated::{RUPRIZZLE_VERSION, SCHEMA_HASH};

        #( #uses )*

        /// The generated `Db` client root.
        #[derive(Debug, Clone)]
        pub struct Db {
            pool: ::ruprizzle::Pool,
        }

        impl Db {
            /// Connect to a database by URL.
            ///
            /// # Errors
            ///
            /// Returns an error if the URL cannot be parsed or the connection fails.
            pub async fn connect(url: &str) -> Result<Self, ::ruprizzle::Error> {
                let pool = ::ruprizzle::Pool::connect(url).await?;
                Ok(Self { pool })
            }

            /// Wrap an existing pool.
            pub fn from_pool(pool: ::ruprizzle::Pool) -> Self {
                Self { pool }
            }

            /// Return the raw `sqlx` pool.
            pub fn raw_pool(&self) -> &::ruprizzle::Pool {
                &self.pool
            }

            #( #repo_methods )*

            /// Drizzle-flavoured `SELECT` entry point.
            pub fn select<M: ::ruprizzle::Model>(&self) -> ::ruprizzle::SelectQuery<'_, M> {
                ::ruprizzle::SelectQuery::new(self.raw_pool())
            }

            /// Drizzle-flavoured `INSERT` entry point.
            pub fn insert<M: ::ruprizzle::Model>(&self) -> ::ruprizzle::InsertQuery<'_, M> {
                ::ruprizzle::InsertQuery::new(self.raw_pool())
            }

            /// Run a closure inside a transaction.
            pub async fn transaction<F, T>(
                &self,
                _f: F,
            ) -> Result<T, ::ruprizzle::Error>
            where
                F: for<'t> FnOnce(&'t mut ::ruprizzle::Tx)
                    -> ::ruprizzle::BoxFuture<'t, Result<T, ::ruprizzle::Error>>,
            {
                let () = std::future::ready(()).await;
                Err(::ruprizzle::Error::NotImplemented)
            }
        }

        /// Common imports for this generated module.
        pub mod prelude {
            pub use super::{
                Db, RUPRIZZLE_VERSION, SCHEMA_HASH,
                #( #prelude_uses )*
            };
            pub use ::ruprizzle::prelude::*;
        }
    };
    format(tokens)
}

fn model_rs(schema: &Schema, model: &Model) -> String {
    let model_name = format_ident!("{}", model.name.as_str());
    let insert_name = format_ident!("{}Insert", model.name.as_str());
    let update_name = format_ident!("{}Update", model.name.as_str());
    let repo_name = format_ident!("{}Repo", model.name.as_str());
    let table = &model.table;
    let docs = doc_attrs(model.docs.as_deref());

    let entity_fields: Vec<_> = model
        .fields
        .values()
        .map(|f| emit_entity_field(schema, f))
        .collect();

    let insert_fields: Vec<_> = model
        .fields
        .values()
        .filter(|f| f.has_column())
        .map(|f| emit_insert_field(schema, f))
        .collect();

    let update_fields: Vec<_> = model
        .fields
        .values()
        .filter(|f| f.has_column())
        .map(|f| emit_update_field(schema, f))
        .collect();

    let column_consts: Vec<_> = model
        .fields
        .values()
        .filter(|f| f.has_column())
        .map(|f| emit_column_const(schema, model, f, table))
        .collect();

    let header = header();
    let tokens = quote! {
        #header

        use ::ruprizzle::serde::{Deserialize, Serialize};
        use ::ruprizzle::sqlx::FromRow;
        use ::ruprizzle::types::chrono::{DateTime, NaiveDate, NaiveTime, Utc};
        use ::ruprizzle::types::{Decimal, Uuid};
        use ::ruprizzle::serde_json::Value as JsonValue;
        use ::ruprizzle::Related;
        use ::ruprizzle::Column;

        #docs
        #[derive(Debug, Clone, PartialEq, FromRow, Serialize, Deserialize)]
        #[serde(crate = "::ruprizzle::serde")]
        pub struct #model_name {
            #( #entity_fields )*
        }

        /// Insert shape: required fields are required, defaulted/optional fields
        /// are `Option` so the database can fill them in.
        #[derive(Debug, Clone, Serialize, Deserialize)]
        #[serde(crate = "::ruprizzle::serde")]
        pub struct #insert_name {
            #( #insert_fields )*
        }

        /// Update shape: every field is `Option` to support explicit nulls.
        #[derive(Debug, Clone, Default, Serialize, Deserialize)]
        #[serde(crate = "::ruprizzle::serde")]
        pub struct #update_name {
            #( #update_fields )*
        }

        impl ::ruprizzle::Model for #model_name {
            const TABLE: &'static str = #table;
        }

        /// Table name for this model.
        pub const TABLE: &str = #table;

        #( #column_consts )*

        /// Prisma-flavoured repository for `#model_name`.
        #[derive(Debug, Clone, Copy)]
        pub struct #repo_name<'a> {
            db: &'a super::Db,
        }

        impl<'a> #repo_name<'a> {
            /// Creates a new repository handle.
            pub(crate) fn new(db: &'a super::Db) -> Self {
                Self { db }
            }

            /// Start a `find_many` query.
            pub fn find_many(&self) -> ::ruprizzle::SelectQuery<'a, #model_name> {
                ::ruprizzle::SelectQuery::new(self.db.raw_pool())
            }

            /// Start an `insert` query.
            pub fn create(&self, _data: #insert_name) -> ::ruprizzle::InsertQuery<'a, #model_name> {
                let _ = _data;
                ::ruprizzle::InsertQuery::new(self.db.raw_pool())
            }
        }
    };
    format(tokens)
}

fn emit_entity_field(schema: &Schema, field: &Field) -> TokenStream {
    let name = safe_field_ident(field.name.as_str());
    let ty = rust_type_tokens(schema, field, field.optional, false);
    let doc = doc_attrs(field.docs.as_deref());

    if !field.has_column() {
        return quote! {
            #doc
            #[sqlx(skip)]
            #[serde(skip_serializing_if = "::ruprizzle::Related::is_absent", default)]
            pub #name: #ty,
        };
    }

    let column = field.column.as_str();
    let sqlx_rename = if name == column {
        None
    } else {
        Some(quote! { #[sqlx(rename = #column)] })
    };

    quote! {
        #doc
        #sqlx_rename
        pub #name: #ty,
    }
}

fn emit_insert_field(schema: &Schema, field: &Field) -> TokenStream {
    let name = safe_field_ident(field.name.as_str());
    let ty = rust_type_tokens(schema, field, false, true);
    let optional = field.optional || field.default.is_some() || field.attrs.is_updated_at;
    let ty = if optional {
        quote! { Option<#ty> }
    } else {
        ty
    };
    let serde_attr = if optional {
        Some(quote! { #[serde(default, skip_serializing_if = "Option::is_none")] })
    } else {
        None
    };

    quote! {
        #serde_attr
        pub #name: #ty,
    }
}

fn emit_update_field(schema: &Schema, field: &Field) -> TokenStream {
    let name = safe_field_ident(field.name.as_str());
    let ty = rust_type_tokens(schema, field, field.optional, false);
    let ty = quote! { Option<#ty> };

    quote! {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub #name: #ty,
    }
}

fn emit_column_const(schema: &Schema, model: &Model, field: &Field, table: &str) -> TokenStream {
    let name = format_ident!("{}", shouty_snake(field.name.as_str()));
    let ty = rust_type_tokens(schema, field, false, false);
    let column = &field.column;
    let model_name = format_ident!("{}", model.name.as_str());

    quote! {
        pub const #name: Column<#model_name, #ty> = Column::new(#table, #column);
    }
}

fn rust_type_tokens(
    schema: &Schema,
    field: &Field,
    wrap_optional: bool,
    base_only: bool,
) -> TokenStream {
    let inner = match &field.kind {
        FieldKind::Scalar(st) => scalar_type_tokens(*st),
        FieldKind::Enum(name) => {
            let name = format_ident!("{}", name.as_str());
            quote! { super::enums::#name }
        }
        FieldKind::List(inner) => match inner.as_ref() {
            FieldKind::Scalar(st) => {
                let inner_ty = scalar_type_tokens(*st);
                quote! { Vec<#inner_ty> }
            }
            FieldKind::Enum(name) => {
                let name = format_ident!("{}", name.as_str());
                quote! { Vec<super::enums::#name> }
            }
            FieldKind::Relation(r) => relation_inner_tokens(schema, r.target.as_str(), true),
            FieldKind::List(_) => {
                // Nested lists are unsupported in v1.
                quote! { () }
            }
        },
        FieldKind::Relation(r) => relation_inner_tokens(schema, r.target.as_str(), false),
    };

    let wrapped = if !base_only && wrap_optional {
        quote! { Option<#inner> }
    } else {
        inner
    };

    if matches!(field.kind, FieldKind::Relation(_) | FieldKind::List(_)) {
        quote! { ::ruprizzle::Related<#wrapped> }
    } else {
        wrapped
    }
}

fn relation_inner_tokens(_schema: &Schema, target: &str, is_list: bool) -> TokenStream {
    let target_module = safe_module_name(target);
    let target = format_ident!("{}", target);
    let module = format_ident!("{}", target_module);
    if is_list {
        quote! { Vec<super::#module::#target> }
    } else {
        // `optional` is applied to `Related` later by the caller.
        quote! { super::#module::#target }
    }
}

fn scalar_type_tokens(st: ScalarType) -> TokenStream {
    match st {
        ScalarType::String => quote! { String },
        ScalarType::Int => quote! { i32 },
        ScalarType::BigInt => quote! { i64 },
        ScalarType::Float => quote! { f64 },
        ScalarType::Decimal => quote! { Decimal },
        ScalarType::Boolean => quote! { bool },
        ScalarType::DateTime => quote! { DateTime<Utc> },
        ScalarType::Date => quote! { NaiveDate },
        ScalarType::Time => quote! { NaiveTime },
        ScalarType::Uuid => quote! { Uuid },
        ScalarType::Json => quote! { JsonValue },
        ScalarType::Bytes => quote! { Vec<u8> },
    }
}

fn doc_attrs(docs: Option<&str>) -> TokenStream {
    match docs {
        Some(text) => {
            let lines: Vec<_> = text.lines().collect();
            quote! { #( #[doc = #lines] )* }
        }
        None => TokenStream::new(),
    }
}

fn safe_field_ident(s: &str) -> Ident {
    let name = naming::snake_case(s);
    safe_ident(&name)
}

fn safe_module_name(s: &str) -> String {
    let name = naming::snake_case(s);
    if is_keyword(&name) {
        format!("{name}_")
    } else {
        name
    }
}

fn safe_ident(s: &str) -> Ident {
    if is_keyword(s) {
        Ident::new_raw(s, Span::call_site())
    } else {
        Ident::new(s, Span::call_site())
    }
}

fn is_keyword(s: &str) -> bool {
    matches!(
        s,
        "as" | "async"
            | "await"
            | "break"
            | "const"
            | "continue"
            | "crate"
            | "dyn"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "abstract"
            | "become"
            | "box"
            | "do"
            | "final"
            | "macro"
            | "override"
            | "priv"
            | "typeof"
            | "unsized"
            | "virtual"
            | "yield"
            | "try"
    )
}

fn shouty_snake(s: &str) -> String {
    naming::snake_case(s).to_ascii_uppercase()
}

fn pascal(s: &str) -> String {
    s.split('_')
        .map(|w| {
            let mut chars = w.chars();
            match chars.next() {
                Some(c) => c.to_uppercase().collect::<String>() + &chars.as_str().to_lowercase(),
                None => String::new(),
            }
        })
        .collect()
}
