//! Token emission helpers.

use std::collections::BTreeMap;

use proc_macro2::{Ident, Span, TokenStream};
use quote::{format_ident, quote};
use ruprizzle_core::ir::{EnumDef, Field, FieldKind, Model, Provider, ScalarType, Schema};
use ruprizzle_parser::naming;

/// Generate all source files for a schema.
///
/// Returns a map from file path (relative to the output directory) to file
/// contents. The caller is responsible for atomic, idempotent disk writes.
pub fn generate_all(schema: &Schema) -> BTreeMap<String, String> {
    let mut files = BTreeMap::new();

    files.insert("_generated.rs".to_owned(), generated_rs(schema));
    files.insert("enums.rs".to_owned(), enums_rs(schema));
    files.insert("mod.rs".to_owned(), mod_rs(schema));

    for model in schema.models.values() {
        let path = format!("{}.rs", safe_module_name(model.name.as_str()));
        files.insert(path, model_rs(schema, model));
    }

    files
}

/// Format a token stream with `prettyplease`.
pub fn format(tokens: TokenStream) -> String {
    let file = syn::parse2::<syn::File>(tokens).expect("generated tokens must be valid Rust");
    prettyplease::unparse(&file)
}

fn header() -> TokenStream {
    quote! {
        // @generated by ruprizzle — DO NOT EDIT.
        // Regenerate with: ruprizzle generate
        #![allow(clippy::all, clippy::pedantic, unused_imports)]
    }
}

fn generated_rs(schema: &Schema) -> String {
    let hash = schema.fingerprint();
    let version = env!("CARGO_PKG_VERSION");
    let header = header();
    let tokens = quote! {
        #header

        /// Schema hash, used to detect stale generated code.
        pub const SCHEMA_HASH: &str = #hash;

        /// ruprizzle version that generated this code.
        pub const RUPRIZZLE_VERSION: &str = #version;
    };
    format(tokens)
}

fn enums_rs(schema: &Schema) -> String {
    let is_postgres = matches!(schema.datasource.provider, Provider::Postgres);
    let enum_items: Vec<_> = schema
        .enums
        .values()
        .map(|e| emit_enum(e, is_postgres))
        .collect();
    let header = header();

    let tokens = quote! {
        #header

        use ::ruprizzle::serde::{Deserialize, Serialize};
        use ::ruprizzle::sqlx::Type;
        use ::ruprizzle::Value;

        #( #enum_items )*
    };
    format(tokens)
}

fn emit_enum(e: &EnumDef, is_postgres: bool) -> TokenStream {
    let name = format_ident!("{}", e.name.as_str());
    let docs = doc_attrs(e.docs.as_deref());
    let type_name = &e.db_name;

    let variants: Vec<_> = e
        .variants
        .values()
        .map(|v| {
            let var = format_ident!("{}", pascal(&v.name));
            let docs = doc_attrs(v.docs.as_deref());
            quote! {
                #docs
                #var,
            }
        })
        .collect();

    let all_variants: Vec<_> = e
        .variants
        .values()
        .map(|v| {
            let var = format_ident!("{}", pascal(&v.name));
            quote! { #name::#var }
        })
        .collect();

    let as_db_arms: Vec<_> = e
        .variants
        .values()
        .map(|v| {
            let var = format_ident!("{}", pascal(&v.name));
            let db = &v.db_name;
            quote! { Self::#var => #db, }
        })
        .collect();

    let from_db_arms: Vec<_> = e
        .variants
        .values()
        .map(|v| {
            let var = format_ident!("{}", pascal(&v.name));
            let db = &v.db_name;
            quote! { #db => Some(Self::#var), }
        })
        .collect();

    let sqlx_attrs = if is_postgres {
        quote! { #[sqlx(type_name = #type_name, rename_all = "SCREAMING_SNAKE_CASE")] }
    } else {
        quote! { #[sqlx(rename_all = "SCREAMING_SNAKE_CASE")] }
    };

    quote! {
        #docs
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Type, Serialize, Deserialize)]
        #sqlx_attrs
        #[serde(crate = "::ruprizzle::serde")]
        pub enum #name {
            #( #variants )*
        }

        impl #name {
            /// All variants in declaration order.
            pub const ALL: &'static [#name] = &[ #( #all_variants ),* ];

            /// The database string for this variant.
            #[must_use]
            pub const fn as_db_str(&self) -> &'static str {
                match self {
                    #( #as_db_arms )*
                }
            }

            /// Parse a database string into a variant.
            #[must_use]
            pub fn from_db_str(s: &str) -> Option<Self> {
                match s {
                    #( #from_db_arms )*
                    _ => None,
                }
            }
        }

        impl std::fmt::Display for #name {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                f.write_str(self.as_db_str())
            }
        }

        impl std::str::FromStr for #name {
            type Err = String;

            fn from_str(s: &str) -> Result<Self, Self::Err> {
                Self::from_db_str(s).ok_or_else(|| format!("unknown {0}: {1}", stringify!(#name), s))
            }
        }

        impl ::ruprizzle::Encodable for #name {
            fn to_value(&self) -> Value {
                Value::Str(self.as_db_str().into())
            }
        }

        #[cfg(feature = "sqlite-rusqlite")]
        impl ::ruprizzle::rusqlite::FromValue for #name {
            fn from_value(value: &::ruprizzle::rusqlite::types::Value) -> Result<Self, ::ruprizzle::Error> {
                let s = <String as ::ruprizzle::rusqlite::FromValue>::from_value(value)?;
                s.parse().map_err(|e: String| {
                    ::ruprizzle::Error::Message(format!(
                        "cannot parse {} from {s:?}: {e}",
                        stringify!(#name)
                    ))
                })
            }
        }
    }
}

fn mod_rs(schema: &Schema) -> String {
    let mods: Vec<_> = schema
        .models
        .values()
        .map(|m| {
            let module = format_ident!("{}", safe_module_name(m.name.as_str()));
            quote! { pub mod #module; }
        })
        .collect();

    let uses: Vec<_> = schema
        .models
        .values()
        .map(|m| {
            let module = format_ident!("{}", safe_module_name(m.name.as_str()));
            let model = format_ident!("{}", m.name.as_str());
            let insert = format_ident!("{}Insert", m.name.as_str());
            let update = format_ident!("{}Update", m.name.as_str());
            let repo = format_ident!("{}Repo", m.name.as_str());
            quote! {
                pub use self::#module::{
                    #insert, #model, #repo, #update,
                };
            }
        })
        .collect();

    let repo_methods: Vec<_> = schema
        .models
        .values()
        .map(|m| {
            let method = format_ident!("{}", naming::snake_case(m.name.as_str()));
            let repo = format_ident!("{}Repo", m.name.as_str());
            quote! {
                /// Entry point for this model's repository.
                pub fn #method(&self) -> #repo<'_> {
                    #repo::new(self)
                }
            }
        })
        .collect();

    let prelude_uses: Vec<_> = schema
        .models
        .values()
        .map(|m| {
            let model = format_ident!("{}", m.name.as_str());
            let insert = format_ident!("{}Insert", m.name.as_str());
            let update = format_ident!("{}Update", m.name.as_str());
            let repo = format_ident!("{}Repo", m.name.as_str());
            let module = format_ident!("{}", safe_module_name(m.name.as_str()));
            quote! { #model, #insert, #update, #repo, #module, }
        })
        .collect();

    let header = header();
    let tokens = quote! {
        #header

        pub mod _generated;
        pub mod enums;

        #( #mods )*

        pub use _generated::{RUPRIZZLE_VERSION, SCHEMA_HASH};

        #( #uses )*

        /// The generated `Db` client root.
        #[derive(Debug, Clone)]
        pub struct Db {
            pool: ::ruprizzle::Pool,
        }

        impl Db {
            /// Connect to a database by URL.
            ///
            /// # Errors
            ///
            /// Returns an error if the URL cannot be parsed or the connection fails.
            pub async fn connect(url: &str) -> Result<Self, ::ruprizzle::Error> {
                let pool = ::ruprizzle::connect(url).await?;
                Ok(Self { pool })
            }

            /// Wrap an existing pool.
            pub fn from_pool(pool: ::ruprizzle::Pool) -> Self {
                Self { pool }
            }

            /// Return the raw `sqlx` pool.
            pub fn raw_pool(&self) -> &::ruprizzle::Pool {
                &self.pool
            }

            #( #repo_methods )*

            /// Drizzle-flavoured `SELECT` entry point.
            pub fn select<M: ::ruprizzle::Model>(&self) -> ::ruprizzle::SelectQuery<'_, M> {
                ::ruprizzle::SelectQuery::new(self.raw_pool())
            }

            /// Drizzle-flavoured `INSERT` entry point.
            pub fn insert<M: ::ruprizzle::Model>(&self) -> ::ruprizzle::InsertQuery<'_, M> {
                ::ruprizzle::InsertQuery::new(self.raw_pool())
            }

            /// Run a closure inside a transaction.
            ///
            /// The closure receives a `&mut ::ruprizzle::Tx` and can execute raw
            /// SQL through it. The transaction is committed if the closure returns
            /// `Ok`, and rolled back if it returns `Err`.
            pub async fn transaction<F, T>(&self, f: F) -> Result<T, ::ruprizzle::Error>
            where
                F: for<'t> FnOnce(&'t mut ::ruprizzle::Tx)
                    -> ::ruprizzle::BoxFuture<'t, Result<T, ::ruprizzle::Error>>,
            {
                let mut tx = ::ruprizzle::Tx::begin(self.raw_pool()).await?;
                match f(&mut tx).await {
                    Ok(v) => {
                        tx.commit().await?;
                        Ok(v)
                    }
                    Err(e) => {
                        tx.rollback().await?;
                        Err(e)
                    }
                }
            }

            /// Run a closure inside a transaction with an explicit isolation level.
            pub async fn transaction_with<F, T>(
                &self,
                level: ::ruprizzle::IsolationLevel,
                f: F,
            ) -> Result<T, ::ruprizzle::Error>
            where
                F: for<'t> FnOnce(&'t mut ::ruprizzle::Tx)
                    -> ::ruprizzle::BoxFuture<'t, Result<T, ::ruprizzle::Error>>,
            {
                let mut tx =
                    ::ruprizzle::Tx::begin_with_isolation(self.raw_pool(), level).await?;
                match f(&mut tx).await {
                    Ok(v) => {
                        tx.commit().await?;
                        Ok(v)
                    }
                    Err(e) => {
                        tx.rollback().await?;
                        Err(e)
                    }
                }
            }

            /// Run a transaction, retrying transient serialization failures.
            ///
            /// Retries only errors [`ruprizzle::is_retryable`] recognises —
            /// Postgres `40001`/`40P01` and SQLite lock contention. A genuine
            /// constraint violation is returned immediately rather than
            /// retried, because retrying it only repeats the work before
            /// failing the same way. `attempts` counts total tries, so
            /// `attempts = 1` disables retrying.
            ///
            /// The closure is `FnMut` because it runs once per attempt.
            pub async fn transaction_retrying<F, T>(
                &self,
                attempts: u32,
                mut f: F,
            ) -> Result<T, ::ruprizzle::Error>
            where
                F: for<'t> FnMut(&'t mut ::ruprizzle::Tx)
                    -> ::ruprizzle::BoxFuture<'t, Result<T, ::ruprizzle::Error>>,
            {
                let mut attempt = 0;
                loop {
                    attempt += 1;
                    let mut tx = ::ruprizzle::Tx::begin(self.raw_pool()).await?;
                    let result = f(&mut tx).await;
                    match result {
                        Ok(v) => {
                            match tx.commit().await {
                                Ok(()) => return Ok(v),
                                Err(e) => {
                                    if attempt >= attempts.max(1)
                                        || !::ruprizzle::is_retryable(&e)
                                    {
                                        return Err(e);
                                    }
                                }
                            }
                        }
                        Err(e) => {
                            tx.rollback().await?;
                            if attempt >= attempts.max(1) || !::ruprizzle::is_retryable(&e) {
                                return Err(e);
                            }
                        }
                    }
                }
            }
        }

        /// Common imports for this generated module.
        pub mod prelude {
            pub use super::{
                Db, RUPRIZZLE_VERSION, SCHEMA_HASH,
                #( #prelude_uses )*
            };
            pub use ::ruprizzle::prelude::*;
        }
    };
    format(tokens)
}

fn model_rs(schema: &Schema, model: &Model) -> String {
    let model_name = format_ident!("{}", model.name.as_str());
    let insert_name = format_ident!("{}Insert", model.name.as_str());
    let update_name = format_ident!("{}Update", model.name.as_str());
    let repo_name = format_ident!("{}Repo", model.name.as_str());
    let table = &model.table;
    let docs = doc_attrs(model.docs.as_deref());

    let entity_fields: Vec<_> = model
        .fields
        .values()
        .map(|f| emit_entity_field(schema, model.name.as_str(), f))
        .collect();

    let insert_fields: Vec<_> = model
        .fields
        .values()
        .filter(|f| f.has_column())
        .map(|f| emit_insert_field(schema, model.name.as_str(), f))
        .collect();

    let update_fields: Vec<_> = model
        .fields
        .values()
        .filter(|f| f.has_column())
        .map(|f| emit_update_field(schema, model.name.as_str(), f))
        .collect();

    let column_consts: Vec<_> = model
        .fields
        .values()
        .filter(|f| f.has_column())
        .map(|f| emit_column_const(schema, model, f, table))
        .collect();

    // The tiebreaker column for deterministic ordering. For a composite key the
    // first column is used: it is not unique on its own, but it is the leading
    // column of the primary-key index, so it is the cheapest useful ordering
    // suffix. Callers needing a total order on a composite key must order by the
    // remaining key columns themselves.
    let primary_key = model
        .primary_key
        .fields
        .first()
        .and_then(|name| model.fields.get(name))
        .map_or_else(|| "id".to_owned(), |f| f.column.clone());

    let relation_helpers: Vec<_> = model
        .fields
        .values()
        .filter(|f| matches!(f.kind, FieldKind::Relation(_) | FieldKind::List(_)))
        .filter_map(|f| emit_relation_helper(schema, model, f))
        .collect();

    let relation_filter_helpers: Vec<_> = model
        .fields
        .values()
        .filter(|f| matches!(f.kind, FieldKind::Relation(_) | FieldKind::List(_)))
        .filter_map(|f| emit_relation_filter_helpers(schema, model, f))
        .collect();

    let insert_sets: Vec<_> = model
        .fields
        .values()
        .filter(|f| f.has_column())
        .map(|f| emit_insert_set(schema, model, f))
        .collect();

    let insert_many_fields: Vec<_> = model
        .fields
        .values()
        .filter(|f| f.has_column())
        .map(emit_insert_many_field)
        .collect();

    let columns: Vec<_> = model
        .fields
        .values()
        .filter(|f| f.has_column())
        .map(|f| f.column.as_str())
        .collect();

    let mut next_index = 0;
    let from_row_fields: Vec<_> = model
        .fields
        .values()
        .map(|f| {
            let idx = if f.has_column() {
                let i = next_index;
                next_index += 1;
                Some(i)
            } else {
                None
            };
            emit_from_row_field(schema, model.name.as_str(), f, idx)
        })
        .collect();

    let mut next_rusqlite_index = 0;
    let rusqlite_from_row_fields: Vec<_> = model
        .fields
        .values()
        .map(|f| {
            let idx = if f.has_column() {
                let i = next_rusqlite_index;
                next_rusqlite_index += 1;
                Some(i)
            } else {
                None
            };
            emit_from_rusqlite_row_field(schema, model.name.as_str(), f, idx)
        })
        .collect();

    let mut next_tokio_postgres_index = 0;
    let tokio_postgres_from_row_fields: Vec<_> = model
        .fields
        .values()
        .map(|f| {
            let idx = if f.has_column() {
                let i = next_tokio_postgres_index;
                next_tokio_postgres_index += 1;
                Some(i)
            } else {
                None
            };
            emit_from_tokio_postgres_row_field(schema, model.name.as_str(), f, idx)
        })
        .collect();

    let header = header();
    let tokens = quote! {
        #header

        use ::ruprizzle::serde::{Deserialize, Serialize};
        use ::ruprizzle::sqlx::any::AnyRow;
        use ::ruprizzle::types::chrono::{DateTime, NaiveDate, NaiveTime, Utc};
        use ::ruprizzle::types::{Decimal, Uuid};
        use ::ruprizzle::serde_json::Value as JsonValue;
        use ::ruprizzle::Related;
        use ::ruprizzle::Column;

        #docs
        #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
        #[serde(crate = "::ruprizzle::serde")]
        pub struct #model_name {
            #( #entity_fields )*
        }

        impl<'r> ::ruprizzle::sqlx::FromRow<'r, AnyRow> for #model_name {
            fn from_row(row: &'r AnyRow) -> Result<Self, ::ruprizzle::sqlx::Error> {
                Ok(Self {
                    #( #from_row_fields )*
                })
            }
        }

        impl<'r> ::ruprizzle::sqlx::FromRow<'r, ::ruprizzle::sqlx::postgres::PgRow> for #model_name {
            fn from_row(row: &'r ::ruprizzle::sqlx::postgres::PgRow) -> Result<Self, ::ruprizzle::sqlx::Error> {
                Ok(Self {
                    #( #from_row_fields )*
                })
            }
        }

        impl<'r> ::ruprizzle::sqlx::FromRow<'r, ::ruprizzle::sqlx::sqlite::SqliteRow> for #model_name {
            fn from_row(row: &'r ::ruprizzle::sqlx::sqlite::SqliteRow) -> Result<Self, ::ruprizzle::sqlx::Error> {
                Ok(Self {
                    #( #from_row_fields )*
                })
            }
        }

        #[cfg(feature = "sqlite-rusqlite")]
        impl ::ruprizzle::rusqlite::FromRusqliteRow for #model_name {
            fn from_rusqlite_row(row: &mut ::ruprizzle::rusqlite::Row) -> Result<Self, ::ruprizzle::Error> {
                Ok(Self {
                    #( #rusqlite_from_row_fields )*
                })
            }
        }

        #[cfg(feature = "postgres-tokio-postgres")]
        impl ::ruprizzle::tokio_postgres::FromTokioPostgresRow for #model_name {
            fn from_tokio_postgres_row(row: &::ruprizzle::tokio_postgres::Row) -> Result<Self, ::ruprizzle::Error> {
                Ok(Self {
                    #( #tokio_postgres_from_row_fields )*
                })
            }
        }

        /// Insert shape: required fields are required, defaulted/optional fields
        /// are `Option` so the database can fill them in.
        #[derive(Debug, Clone, Serialize, Deserialize)]
        #[serde(crate = "::ruprizzle::serde")]
        pub struct #insert_name {
            #( #insert_fields )*
        }

        /// Update shape: every field is `Option` to support explicit nulls.
        #[derive(Debug, Clone, Default, Serialize, Deserialize)]
        #[serde(crate = "::ruprizzle::serde")]
        pub struct #update_name {
            #( #update_fields )*
        }

        impl ::ruprizzle::Model for #model_name {
            const TABLE: &'static str = #table;
            const PRIMARY_KEY: &'static str = #primary_key;
            const COLUMNS: &'static [&'static str] = &[ #( #columns ),* ];
        }

        /// Table name for this model.
        pub const TABLE: &str = #table;

        #( #column_consts )*

        #( #relation_helpers )*

        #( #relation_filter_helpers )*

        /// Prisma-flavoured repository for `#model_name`.
        #[derive(Debug, Clone, Copy)]
        pub struct #repo_name<'a> {
            db: &'a super::Db,
        }

        impl<'a> #repo_name<'a> {
            /// Creates a new repository handle.
            pub(crate) fn new(db: &'a super::Db) -> Self {
                Self { db }
            }

            /// Start a `find_many` query.
            pub fn find_many(&self) -> ::ruprizzle::SelectQuery<'a, #model_name> {
                ::ruprizzle::SelectQuery::new(self.db.raw_pool())
            }

            /// Start an `insert` query.
            pub fn create(&self, _data: #insert_name) -> ::ruprizzle::InsertQuery<'a, #model_name> {
                let mut insert = ::ruprizzle::InsertQuery::new(self.db.raw_pool());
                #( #insert_sets )*
                insert
            }

            /// Start a multi-row `insert` query.
            pub fn create_many(
                &self,
                _data: Vec<#insert_name>,
            ) -> ::ruprizzle::InsertManyQuery<'a, #model_name> {
                let mut q = ::ruprizzle::InsertManyQuery::new(self.db.raw_pool());
                for _row in _data {
                    q = q.row([ #( #insert_many_fields )* ]);
                }
                q
            }

            /// Start an `update` query.
            pub fn update(&self) -> ::ruprizzle::UpdateQuery<'a, #model_name> {
                ::ruprizzle::UpdateQuery::new(self.db.raw_pool())
            }

            /// Start a `delete` query.
            pub fn delete(&self) -> ::ruprizzle::DeleteQuery<'a, #model_name> {
                ::ruprizzle::DeleteQuery::new(self.db.raw_pool())
            }
        }
    };
    format(tokens)
}

fn emit_entity_field(schema: &Schema, owner: &str, field: &Field) -> TokenStream {
    let name = safe_field_ident(field.name.as_str());
    let ty = rust_type_tokens(schema, owner, field, field.optional, false);
    let doc = doc_attrs(field.docs.as_deref());

    if !field.has_column() {
        return quote! {
            #doc
            #[serde(skip_serializing_if = "::ruprizzle::Related::is_absent", default)]
            pub #name: #ty,
        };
    }

    quote! {
        #doc
        pub #name: #ty,
    }
}

fn emit_from_row_field(
    schema: &Schema,
    owner: &str,
    field: &Field,
    idx: Option<usize>,
) -> TokenStream {
    let name = safe_field_ident(field.name.as_str());

    if !field.has_column() {
        return quote! { #name: ::ruprizzle::Related::default(), };
    }

    let optional = field.optional;
    let _inner = rust_type_tokens(schema, owner, field, false, true);
    let idx = syn::Index::from(idx.unwrap_or(0));

    let expr = match &field.kind {
        ruprizzle_core::ir::FieldKind::Scalar(st) => match st {
            ruprizzle_core::ir::ScalarType::String
            | ruprizzle_core::ir::ScalarType::Int
            | ruprizzle_core::ir::ScalarType::BigInt
            | ruprizzle_core::ir::ScalarType::Float => {
                let helper = format_ident!(
                    "{}",
                    if optional {
                        "direct_opt_idx"
                    } else {
                        "direct_idx"
                    }
                );
                quote! { ::ruprizzle::decode::#helper(row, #idx)? }
            }
            ruprizzle_core::ir::ScalarType::Boolean => {
                let helper = format_ident!(
                    "{}",
                    if optional {
                        "boolean_opt_idx"
                    } else {
                        "boolean_idx"
                    }
                );
                quote! { ::ruprizzle::decode::#helper(row, #idx)? }
            }
            ruprizzle_core::ir::ScalarType::Decimal
            | ruprizzle_core::ir::ScalarType::DateTime
            | ruprizzle_core::ir::ScalarType::Date
            | ruprizzle_core::ir::ScalarType::Time
            | ruprizzle_core::ir::ScalarType::Uuid => {
                let helper =
                    format_ident!("{}", if optional { "text_opt_idx" } else { "text_idx" });
                quote! { ::ruprizzle::decode::#helper(row, #idx)? }
            }
            ruprizzle_core::ir::ScalarType::Json => {
                let helper =
                    format_ident!("{}", if optional { "json_opt_idx" } else { "json_idx" });
                quote! { ::ruprizzle::decode::#helper(row, #idx)? }
            }
            ruprizzle_core::ir::ScalarType::Bytes => {
                let helper = format_ident!(
                    "{}",
                    if optional {
                        "bytes_opt_idx"
                    } else {
                        "bytes_idx"
                    }
                );
                quote! { ::ruprizzle::decode::#helper(row, #idx)? }
            }
        },
        ruprizzle_core::ir::FieldKind::Enum(_) => {
            let helper = format_ident!("{}", if optional { "text_opt_idx" } else { "text_idx" });
            quote! { ::ruprizzle::decode::#helper(row, #idx)? }
        }
        _ => {
            let helper = format_ident!(
                "{}",
                if optional {
                    "direct_opt_idx"
                } else {
                    "direct_idx"
                }
            );
            quote! { ::ruprizzle::decode::#helper(row, #idx)? }
        }
    };

    quote! { #name: #expr, }
}

fn emit_from_rusqlite_row_field(
    schema: &Schema,
    owner: &str,
    field: &Field,
    idx: Option<usize>,
) -> TokenStream {
    let name = safe_field_ident(field.name.as_str());

    if !field.has_column() {
        return quote! { #name: ::ruprizzle::Related::default(), };
    }

    let idx = syn::Index::from(idx.unwrap_or(0));
    let ty = rust_type_tokens(schema, owner, field, field.optional, false);

    quote! { #name: row.take::<#ty>(#idx)?, }
}

fn emit_from_tokio_postgres_row_field(
    schema: &Schema,
    owner: &str,
    field: &Field,
    idx: Option<usize>,
) -> TokenStream {
    let name = safe_field_ident(field.name.as_str());

    if !field.has_column() {
        return quote! { #name: ::ruprizzle::Related::default(), };
    }

    let idx = syn::Index::from(idx.unwrap_or(0));
    let ty = rust_type_tokens(schema, owner, field, false, false);

    match &field.kind {
        ruprizzle_core::ir::FieldKind::Enum(_) => {
            if field.optional {
                quote! {
                    #name: row.try_get::<usize, Option<String>>(#idx)
                        .map_err(::ruprizzle::Error::TokioPostgres)?
                        .map(|s| s.parse::<#ty>().map_err(|e| ::ruprizzle::Error::Message(format!("cannot parse enum: {e}"))))
                        .transpose()?,
                }
            } else {
                quote! {
                    #name: row.try_get::<usize, String>(#idx)
                        .map_err(::ruprizzle::Error::TokioPostgres)?
                        .parse::<#ty>()
                        .map_err(|e| ::ruprizzle::Error::Message(format!("cannot parse enum: {e}")))?,
                }
            }
        }
        _ => {
            if field.optional {
                quote! { #name: row.try_get::<usize, Option<#ty>>(#idx).map_err(::ruprizzle::Error::TokioPostgres)?, }
            } else {
                quote! { #name: row.try_get::<usize, #ty>(#idx).map_err(::ruprizzle::Error::TokioPostgres)?, }
            }
        }
    }
}

fn emit_insert_field(schema: &Schema, owner: &str, field: &Field) -> TokenStream {
    let name = safe_field_ident(field.name.as_str());
    let ty = rust_type_tokens(schema, owner, field, false, true);
    let optional = field.optional || field.default.is_some() || field.attrs.is_updated_at;
    let ty = if optional {
        quote! { Option<#ty> }
    } else {
        ty
    };
    let serde_attr = if optional {
        Some(quote! { #[serde(default, skip_serializing_if = "Option::is_none")] })
    } else {
        None
    };

    quote! {
        #serde_attr
        pub #name: #ty,
    }
}

fn emit_update_field(schema: &Schema, owner: &str, field: &Field) -> TokenStream {
    let name = safe_field_ident(field.name.as_str());
    let ty = rust_type_tokens(schema, owner, field, field.optional, false);
    let ty = quote! { Option<#ty> };

    quote! {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub #name: #ty,
    }
}

fn emit_column_const(schema: &Schema, model: &Model, field: &Field, table: &str) -> TokenStream {
    let name = format_ident!("{}", shouty_snake(field.name.as_str()));
    let ty = rust_type_tokens(schema, model.name.as_str(), field, false, false);
    let column = &field.column;
    let model_name = format_ident!("{}", model.name.as_str());

    quote! {
        pub const #name: Column<#model_name, #ty> = Column::new(#table, #column);
    }
}

fn emit_insert_set(_schema: &Schema, _model: &Model, field: &Field) -> TokenStream {
    let field_ident = safe_field_ident(field.name.as_str());
    let col = format_ident!("{}", shouty_snake(field.name.as_str()));
    let optional = field.optional || field.default.is_some() || field.attrs.is_updated_at;

    if optional {
        quote! { insert = insert.set_optional(#col, _data.#field_ident); }
    } else {
        quote! { insert = insert.set(#col, _data.#field_ident); }
    }
}

fn emit_insert_many_field(field: &Field) -> TokenStream {
    let field_ident = safe_field_ident(field.name.as_str());
    let col_name = field.column.as_str();

    quote! { (#col_name, ::ruprizzle::Encodable::to_value(&_row.#field_ident)), }
}

fn rust_type_tokens(
    schema: &Schema,
    owner: &str,
    field: &Field,
    wrap_optional: bool,
    base_only: bool,
) -> TokenStream {
    let inner = match &field.kind {
        FieldKind::Scalar(st) => scalar_type_tokens(*st),
        FieldKind::Enum(name) => {
            let name = format_ident!("{}", name.as_str());
            quote! { super::enums::#name }
        }
        FieldKind::List(inner) => match inner.as_ref() {
            FieldKind::Scalar(st) => {
                let inner_ty = scalar_type_tokens(*st);
                quote! { Vec<#inner_ty> }
            }
            FieldKind::Enum(name) => {
                let name = format_ident!("{}", name.as_str());
                quote! { Vec<super::enums::#name> }
            }
            FieldKind::Relation(r) => relation_inner_tokens(schema, owner, r.target.as_str(), true),
            FieldKind::List(_) => {
                // Nested lists are unsupported in v1.
                quote! { () }
            }
        },
        FieldKind::Relation(r) => relation_inner_tokens(schema, owner, r.target.as_str(), false),
    };

    let is_relation = matches!(field.kind, FieldKind::Relation(_) | FieldKind::List(_));

    let wrapped = if !base_only && wrap_optional && !is_relation {
        quote! { Option<#inner> }
    } else {
        inner
    };

    if is_relation {
        quote! { ::ruprizzle::Related<#wrapped> }
    } else {
        wrapped
    }
}

fn relation_inner_tokens(
    _schema: &Schema,
    owner: &str,
    target: &str,
    is_list: bool,
) -> TokenStream {
    let is_self = owner == target;
    let target_module = safe_module_name(target);
    let target_ident = format_ident!("{}", target);
    let module = format_ident!("{}", target_module);
    if is_list {
        // `Vec` is already a pointer, so a self-referential list is finite.
        quote! { Vec<super::#module::#target_ident> }
    } else if is_self {
        // A self-relation stored inline would make the struct infinitely
        // sized (`Thread` containing a `Thread`). `Box` breaks the cycle; it
        // is only reached on the self-referential case, so no other model
        // pays for the indirection.
        quote! { Option<Box<super::#module::#target_ident>> }
    } else {
        // Single relations are always `Option` because a row might not have a
        // matching child (LEFT JOIN semantics). `Related` wraps the `Option`.
        quote! { Option<super::#module::#target_ident> }
    }
}

fn scalar_type_tokens(st: ScalarType) -> TokenStream {
    match st {
        ScalarType::String => quote! { String },
        ScalarType::Int => quote! { i32 },
        ScalarType::BigInt => quote! { i64 },
        ScalarType::Float => quote! { f64 },
        ScalarType::Decimal => quote! { Decimal },
        ScalarType::Boolean => quote! { bool },
        ScalarType::DateTime => quote! { DateTime<Utc> },
        ScalarType::Date => quote! { NaiveDate },
        ScalarType::Time => quote! { NaiveTime },
        ScalarType::Uuid => quote! { Uuid },
        ScalarType::Json => quote! { JsonValue },
        ScalarType::Bytes => quote! { Vec<u8> },
    }
}

fn doc_attrs(docs: Option<&str>) -> TokenStream {
    match docs {
        Some(text) => {
            let lines: Vec<_> = text.lines().collect();
            quote! { #( #[doc = #lines] )* }
        }
        None => TokenStream::new(),
    }
}

fn safe_field_ident(s: &str) -> Ident {
    let name = naming::snake_case(s);
    safe_ident(&name)
}

fn safe_module_name(s: &str) -> String {
    let name = naming::snake_case(s);
    if is_keyword(&name) {
        format!("{name}_")
    } else {
        name
    }
}

fn safe_ident(s: &str) -> Ident {
    if is_keyword(s) {
        Ident::new_raw(s, Span::call_site())
    } else {
        Ident::new(s, Span::call_site())
    }
}

fn is_keyword(s: &str) -> bool {
    matches!(
        s,
        "as" | "async"
            | "await"
            | "break"
            | "const"
            | "continue"
            | "crate"
            | "dyn"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "abstract"
            | "become"
            | "box"
            | "do"
            | "final"
            | "macro"
            | "override"
            | "priv"
            | "typeof"
            | "unsized"
            | "virtual"
            | "yield"
            | "try"
    )
}

fn shouty_snake(s: &str) -> String {
    naming::snake_case(s).to_ascii_uppercase()
}

fn pascal(s: &str) -> String {
    s.split('_')
        .map(|w| {
            let mut chars = w.chars();
            match chars.next() {
                Some(c) => c.to_uppercase().collect::<String>() + &chars.as_str().to_lowercase(),
                None => String::new(),
            }
        })
        .collect()
}

fn find_field_by_column<'a>(model: &'a Model, column: &str) -> Option<&'a Field> {
    model
        .fields
        .values()
        .find(|f| f.has_column() && f.column.as_str() == column)
}

fn relation_key_type(schema: &Schema, owner: &str, field: &Field) -> TokenStream {
    // Return the inner, non-optional type of a column-bearing key field.
    // Optional relation keys are not supported for generated include helpers
    // in v1; callers will get a type error at compile time.
    rust_type_tokens(schema, owner, field, false, true)
}

fn emit_relation_helper(schema: &Schema, model: &Model, field: &Field) -> Option<TokenStream> {
    let model_name = format_ident!("{}", model.name.as_str());
    let rel_ref = match &field.kind {
        FieldKind::Relation(r) => r,
        FieldKind::List(inner) => match inner.as_ref() {
            FieldKind::Relation(r) => r,
            _ => return None,
        },
        _ => return None,
    };

    let rel_index = rel_ref.resolved?;
    let rel = schema.relations.get(rel_index)?;
    let is_list = matches!(field.kind, FieldKind::List(_));
    let is_owner = model.name == rel.owner;

    let (parent_name, child_name, parent_key_col, child_key_col) = if is_owner {
        (
            &rel.owner,
            &rel.target,
            rel.owner_cols.first()?,
            rel.target_cols.first()?,
        )
    } else {
        (
            &rel.target,
            &rel.owner,
            rel.target_cols.first()?,
            rel.owner_cols.first()?,
        )
    };

    // The parent model is always the model we are generating code for.
    let parent_model = schema.models.get(parent_name)?;
    let child_model = schema.models.get(child_name)?;

    let parent_key_field = find_field_by_column(parent_model, parent_key_col)?;
    let child_key_field = find_field_by_column(child_model, child_key_col)?;

    // Optional foreign keys are not supported by the include machinery in v1:
    // `Key` must be `Encodable + Hash + Eq` for the batched load, and
    // `Option<T>` is not `Encodable`. Skip the helper rather than emitting a
    // getter whose type cannot line up — generated code that does not compile
    // is a far worse failure than a missing convenience method, and it is what
    // this used to do (`social`'s optional `Thread.parentId` broke the build).
    // The relation field, its column token, and hand-written queries all still
    // work; only the generated `include` helper is absent.
    if parent_key_field.optional || child_key_field.optional {
        return None;
    }

    // Key types must match.
    let key_type = relation_key_type(schema, model.name.as_str(), parent_key_field);
    let child_key_type = relation_key_type(schema, model.name.as_str(), child_key_field);
    if key_type.to_string() != child_key_type.to_string() {
        return None;
    }

    let parent_field_ident = safe_field_ident(field.name.as_str());
    let parent_key_ident = safe_field_ident(parent_key_field.name.as_str());
    let child_key_ident = safe_field_ident(child_key_field.name.as_str());
    let child_key_const = format_ident!("{}", shouty_snake(child_key_field.name.as_str()));

    let child_module = safe_module_name(child_name.as_str());
    let child_module_ident = format_ident!("{}", child_module);
    let child_type = format_ident!("{}", child_name.as_str());

    let helper_name = safe_field_ident(field.name.as_str());

    // A self-referential to-one field is stored boxed (see
    // `relation_inner_tokens`), so the setter has to box the loaded value to
    // match. Every other relation assigns straight through.
    let is_self_to_one = !is_list && child_name.as_str() == model.name.as_str();
    let one_setter = if is_self_to_one {
        quote! {
            |__row, __loaded| {
                __row.#parent_field_ident = match __loaded {
                    ::ruprizzle::Related::Absent => ::ruprizzle::Related::Absent,
                    ::ruprizzle::Related::Loaded(__v) => {
                        ::ruprizzle::Related::Loaded(__v.map(Box::new))
                    }
                };
            }
        }
    } else {
        quote! { |__row, __loaded| __row.#parent_field_ident = __loaded }
    };

    Some(if is_list {
        quote! {
            /// Returns an `IncludeList` for this relation.
            pub fn #helper_name() -> ::ruprizzle::IncludeList<'static, #model_name, super::#child_module_ident::#child_type, #key_type, ()> {
                ::ruprizzle::IncludeList::new(
                    |__row| __row.#parent_key_ident,
                    |__row, __loaded| __row.#parent_field_ident = __loaded,
                    super::#child_module_ident::#child_key_const,
                    |__child| __child.#child_key_ident,
                )
            }
        }
    } else {
        quote! {
            /// Returns an `IncludeOne` for this relation.
            pub fn #helper_name() -> ::ruprizzle::IncludeOne<'static, #model_name, super::#child_module_ident::#child_type, #key_type, ()> {
                ::ruprizzle::IncludeOne::new(
                    |__row| __row.#parent_key_ident,
                    #one_setter,
                    super::#child_module_ident::#child_key_const,
                    |__child| __child.#child_key_ident,
                )
            }
        }
    })
}

fn emit_relation_filter_helpers(
    schema: &Schema,
    model: &Model,
    field: &Field,
) -> Option<TokenStream> {
    let model_name = format_ident!("{}", model.name.as_str());
    let rel_ref = match &field.kind {
        FieldKind::Relation(r) => r,
        FieldKind::List(inner) => match inner.as_ref() {
            FieldKind::Relation(r) => r,
            _ => return None,
        },
        _ => return None,
    };

    let rel_index = rel_ref.resolved?;
    let rel = schema.relations.get(rel_index)?;
    let is_owner = model.name == rel.owner;

    let (parent_table, parent_col, child, child_col) = if is_owner {
        (
            &model.table,
            rel.owner_cols.first()?,
            &rel.target,
            rel.target_cols.first()?,
        )
    } else {
        (
            &model.table,
            rel.target_cols.first()?,
            &rel.owner,
            rel.owner_cols.first()?,
        )
    };

    let child_model = schema.models.get(child)?;
    let child_table = &child_model.table;
    let child_module = safe_module_name(child.as_str());
    let child_module_ident = format_ident!("{}", child_module);
    let child_type = format_ident!("{}", child.as_str());

    let base = safe_field_ident(field.name.as_str());
    let some_name = format_ident!("{}_some", base);
    let none_name = format_ident!("{}_none", base);
    let every_name = format_ident!("{}_every", base);

    Some(quote! {
        /// Returns a filter for parents that have at least one matching child.
        pub fn #some_name(f: ::ruprizzle::Filter<super::#child_module_ident::#child_type>) -> ::ruprizzle::Filter<#model_name> {
            ::ruprizzle::Filter::new(::ruprizzle::FilterNode::Exists {
                child_table: #child_table,
                child_col: #child_col,
                parent_table: #parent_table,
                parent_col: #parent_col,
                filter: Box::new(f.node),
                negated: false,
            })
        }

        /// Returns a filter for parents that have no matching child.
        pub fn #none_name(f: ::ruprizzle::Filter<super::#child_module_ident::#child_type>) -> ::ruprizzle::Filter<#model_name> {
            ::ruprizzle::Filter::new(::ruprizzle::FilterNode::Exists {
                child_table: #child_table,
                child_col: #child_col,
                parent_table: #parent_table,
                parent_col: #parent_col,
                filter: Box::new(f.node),
                negated: true,
            })
        }

        /// Returns a filter for parents where every matching child satisfies `f`.
        /// Vacuously true for parents with no children.
        pub fn #every_name(f: ::ruprizzle::Filter<super::#child_module_ident::#child_type>) -> ::ruprizzle::Filter<#model_name> {
            ::ruprizzle::Filter::new(::ruprizzle::FilterNode::Exists {
                child_table: #child_table,
                child_col: #child_col,
                parent_table: #parent_table,
                parent_col: #parent_col,
                filter: Box::new((!f).node),
                negated: true,
            })
        }
    })
}
