//! Compile-test for generated code.
//!
//! Generates all four example schemas for all three SQL dialects, writes them as
//! sibling modules of one throw-away crate in `target/generated-check`, and runs
//! a single `cargo check` over the lot. Generated code refers to its neighbours
//! only through `super::`, never through absolute `crate::` paths, which is what
//! lets the twelve variants coexist in one crate and keeps this to one check
//! instead of twelve.

use std::fs;
use std::process::Command;

use ruprizzle_codegen::generate_all;
use ruprizzle_core::ir::Provider;
use ruprizzle_parser::parse;

const EXAMPLES: [&str; 4] = ["blog", "ecommerce", "saas-tenant", "minimal"];

#[test]
#[ignore = "runs cargo check over 12 generated crates; expensive (CI: --ignored)"]
fn all_examples_all_dialects_compile() {
    let workspace = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf();

    let out = workspace.join("target/generated-check");
    if out.exists() {
        fs::remove_dir_all(&out).unwrap();
    }
    fs::create_dir_all(out.join("src")).unwrap();

    let cargo_toml = r#"[package]
name = "generated-check"
version = "0.0.0"
edition = "2024"
rust-version = "1.85"

[workspace]

[features]
sqlite-rusqlite = []
postgres-tokio-postgres = []

[dependencies]
ruprizzle = { path = "../../crates/runtime" }
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "macros", "uuid", "chrono", "json", "rust_decimal", "any", "postgres", "sqlite", "mysql"] }
"#;
    fs::write(out.join("Cargo.toml"), cargo_toml).unwrap();

    let mut lib_rs = String::from("// @generated by the codegen compile test.\n");

    for example in EXAMPLES {
        for (label, provider) in [
            ("postgres", Provider::Postgres),
            ("sqlite", Provider::Sqlite),
            ("mysql", Provider::Mysql),
        ] {
            let schema_src =
                fs::read_to_string(workspace.join(format!("examples/{example}/schema.ruprizzle")))
                    .unwrap();
            let mut schema = parse("schema.ruprizzle", &schema_src).unwrap();
            schema.datasource.provider = provider;
            let files = generate_all(&schema);

            let module = format!("{}_{label}", example.replace('-', "_"));
            let dir = out.join("src").join(&module);
            fs::create_dir_all(&dir).unwrap();
            for (path, content) in files {
                fs::write(dir.join(&path), content).unwrap();
            }
            // Each variant's `mod.rs` is the generated one, so the module just
            // points at the directory.
            lib_rs.push_str(&format!("pub mod {module};\n"));
        }
    }

    fs::write(out.join("src/lib.rs"), lib_rs).unwrap();

    let output = Command::new("cargo")
        .arg("check")
        .arg("--manifest-path")
        .arg(out.join("Cargo.toml"))
        .output()
        .expect("cargo should be on PATH");

    assert!(
        output.status.success(),
        "generated crates did not compile:\n{}",
        String::from_utf8_lossy(&output.stderr)
    );
}

/// The same matrix under `clippy::pedantic`, which is the actual wording of the
/// G3 exit gate. Split from the check above so a pedantic-only regression is
/// distinguishable from a hard compile error.
#[test]
#[ignore = "runs cargo clippy over 12 generated crates; expensive (CI: --ignored)"]
fn generated_code_is_pedantic_clean() {
    let workspace = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf();
    let manifest = workspace.join("target/generated-check/Cargo.toml");

    assert!(
        manifest.exists(),
        "run all_examples_all_dialects_compile first (it materialises the crate)"
    );

    let output = Command::new("cargo")
        .arg("clippy")
        .arg("--manifest-path")
        .arg(&manifest)
        .arg("--")
        .arg("-W")
        .arg("clippy::pedantic")
        .arg("-D")
        .arg("warnings")
        .output()
        .expect("cargo should be on PATH");

    assert!(
        output.status.success(),
        "generated crates are not pedantic-clean:\n{}",
        String::from_utf8_lossy(&output.stderr)
    );
}
