[package]
name        = "ruprizzle-integration-tests"
description = "Cross-crate integration tests for the ruprizzle ORM"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
homepage.workspace     = true
publish     = false

[dependencies]
ruprizzle-core = { workspace = true }

[dev-dependencies]
ruprizzle         = { workspace = true }
ruprizzle-dialect = { workspace = true }
ruprizzle-migrate = { workspace = true }
ruprizzle-parser  = { workspace = true }
ruprizzle-testkit = { workspace = true }
futures-core      = "0.3"
insta             = { workspace = true }
miette            = { workspace = true, features = ["fancy"] }
sqlx              = { workspace = true }
tempfile          = { workspace = true }
tokio             = { workspace = true }

[features]
sqlite-rusqlite = [
    "ruprizzle/sqlite-rusqlite",
    "ruprizzle-migrate/sqlite-rusqlite",
    "ruprizzle-testkit/sqlite-rusqlite",
]
postgres-tokio-postgres = ["ruprizzle/postgres-tokio-postgres"]
