[package]
name        = "ruprizzle-parser"
description = "Schema DSL parser for the ruprizzle ORM"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true
homepage.workspace     = true
readme                 = "README.md"
documentation          = "https://docs.rs/ruprizzle-parser"
keywords    = ["orm", "sql", "database", "parser", "schema"]
categories  = ["database"]

[dependencies]
ruprizzle-core = { workspace = true }
indexmap       = { workspace = true }
pest           = { workspace = true }
pest_derive    = { workspace = true }
miette         = { workspace = true }

[dev-dependencies]
insta  = { workspace = true }
miette = { workspace = true, features = ["fancy"] }
