[package]
name        = "ruprizzle-migrate"
description = "Schema diffing and migration engine for the ruprizzle ORM"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true
homepage.workspace     = true
readme                 = "README.md"
documentation          = "https://docs.rs/ruprizzle-migrate"
keywords    = ["orm", "sql", "database", "migrations", "schema"]
categories  = ["database"]

[dependencies]
ruprizzle-core    = { workspace = true }
ruprizzle-dialect = { workspace = true }
ruprizzle-parser  = { workspace = true }
serde             = { workspace = true }
serde_json        = { workspace = true }
thiserror         = { workspace = true }
sha2              = { workspace = true }
chrono            = { workspace = true }
sqlx              = { workspace = true, features = ["any", "postgres", "sqlite"] }
tracing            = { version = "0.1", default-features = false, features = ["std"] }

[dev-dependencies]
tokio  = { workspace = true }
tempfile = { workspace = true }

