//! The `ruprizzle` command-line interface.
//!
//! The command surface is declared in full from P0 so that the shape of the tool
//! is fixed early and the `migrate dev` / `migrate deploy` split — the guard that
//! keeps a prototyping command away from production data — is structural rather
//! than something bolted on later.
//!
//! Subcommands are implemented incrementally: P6 delivers `migrate deploy`,
//! `migrate status`, and `db push` (schema push without migration files).
//! The remaining commands are still placeholders.

#![forbid(unsafe_code)]
#![warn(clippy::pedantic)]

use std::path::Path;
use std::process::ExitCode;

use clap::{Parser, Subcommand};

#[derive(Parser, Debug)]
#[command(
    name = "ruprizzle",
    version,
    about = "A schema-first ORM for Rust",
    long_about = "Write a schema, get typed entities, a query builder that shows you \
                  its SQL, and migrations generated by diffing your schema."
)]
struct Cli {
    /// Path to the schema file.
    #[arg(
        long,
        global = true,
        default_value = "schema.ruprizzle",
        env = "RUPRIZZLE_SCHEMA"
    )]
    schema: String,

    /// Print the resolved configuration and where each value came from.
    #[arg(long, global = true)]
    verbose: bool,

    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand, Debug)]
enum Command {
    /// Scaffold a schema, `.env`, and migrations directory.
    Init {
        /// Which database this project targets.
        #[arg(long, default_value = "postgres")]
        provider: String,
    },

    /// Parse the schema and emit Rust into the generator's output directory.
    Generate {
        /// Regenerate on every change to the schema file.
        #[arg(long)]
        watch: bool,
    },

    /// Parse and validate the schema without writing anything. For CI.
    Validate,

    /// Rewrite the schema file in canonical form.
    Format,

    /// Migration commands.
    #[command(subcommand)]
    Migrate(MigrateCommand),

    /// Direct-to-database commands that bypass migration history.
    #[command(subcommand)]
    Db(DbCommand),
}

#[derive(Subcommand, Debug)]
enum MigrateCommand {
    /// Diff the schema, write a migration, apply it, and regenerate the client.
    ///
    /// The development workflow. Prompts before anything destructive.
    Dev {
        /// Name for the generated migration directory.
        #[arg(long)]
        name: Option<String>,
        /// Permit changes that discard data.
        #[arg(long)]
        accept_data_loss: bool,
        /// Write the migration but do not apply it.
        #[arg(long)]
        create_only: bool,
    },
    /// Apply pending migrations. No diffing, no prompts, no codegen.
    ///
    /// The production and CI workflow.
    Deploy,
    /// Report applied, pending, and drifted state.
    Status,
    /// Record a migration as applied without running it.
    Resolve {
        /// Migration directory name.
        id: String,
    },
    /// Drop everything and replay the migration history. Development only.
    Reset {
        /// Skip the confirmation prompt.
        #[arg(long)]
        force: bool,
    },
}

#[derive(Subcommand, Debug)]
enum DbCommand {
    /// Push the schema straight to the database with no migration file.
    Push {
        /// Permit changes that discard data.
        #[arg(long)]
        accept_data_loss: bool,
    },
    /// Run the project's seed script.
    Seed,
}

fn owning_phase(command: &Command) -> Option<(&'static str, &'static str)> {
    match command {
        Command::Generate { .. } | Command::Validate => {
            Some(("P1-P3", "ImplPlan02SchemaDslParser.md"))
        }
        Command::Migrate(MigrateCommand::Dev { .. }) | Command::Db(DbCommand::Push { .. }) => {
            // `migrate dev` and `db push` still rely on codegen/round-trip polish.
            Some(("P6-P7", "ImplPlan07Migrations.md"))
        }
        Command::Migrate(
            MigrateCommand::Deploy
            | MigrateCommand::Status
            | MigrateCommand::Resolve { .. }
            | MigrateCommand::Reset { .. },
        ) => None,
        Command::Init { .. } | Command::Format | Command::Db(DbCommand::Seed) => {
            Some(("P7", "ImplPlan08CliDx.md"))
        }
    }
}

#[tokio::main]
async fn main() -> ExitCode {
    let cli = Cli::parse();

    if cli.verbose {
        eprintln!("schema path: {}", cli.schema);
    }

    match run(cli).await {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("ruprizzle: {e}");
            ExitCode::FAILURE
        }
    }
}

async fn run(cli: Cli) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    match &cli.command {
        Command::Validate => {
            validate(&cli.schema)?;
            Ok(())
        }
        Command::Migrate(MigrateCommand::Deploy) => {
            migrate_deploy(&cli.schema, "migrations", false).await
        }
        Command::Migrate(MigrateCommand::Status) => migrate_status(&cli.schema, "migrations").await,
        _ => {
            if let Some((phase, doc)) = owning_phase(&cli.command) {
                Err(format!(
                    "this command is not implemented yet. It arrives in phase {phase}. \
                     See ProjectPlan/ImplementationPlan/{doc} for details."
                )
                .into())
            } else {
                Err("this command is implemented but failed to dispatch".into())
            }
        }
    }
}

fn validate(schema_path: &str) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    let source = std::fs::read_to_string(schema_path)?;
    let _ = ruprizzle_parser::parse(schema_path, &source)?;
    println!("{schema_path} is valid.");
    Ok(())
}

fn resolve_database_url(
    schema_path: &str,
) -> Result<String, Box<dyn std::error::Error + Send + Sync>> {
    let source = std::fs::read_to_string(schema_path)?;
    let schema = ruprizzle_parser::parse(schema_path, &source)?;

    match &schema.datasource.url {
        ruprizzle_core::ir::DatasourceUrl::Literal(url) => Ok(url.clone()),
        ruprizzle_core::ir::DatasourceUrl::Env(var) => std::env::var(var).map_err(|_| {
            format!("environment variable {var} (from datasource.url) is not set").into()
        }),
    }
}

async fn connect(url: &str) -> Result<sqlx::AnyPool, Box<dyn std::error::Error + Send + Sync>> {
    sqlx::any::install_default_drivers();
    Ok(sqlx::AnyPool::connect(url).await?)
}

async fn migrate_deploy(
    schema_path: &str,
    migrations_dir: &str,
    accept_data_loss: bool,
) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    validate(schema_path)?;

    let url = resolve_database_url(schema_path)?;
    let pool = connect(&url).await?;

    if !Path::new(migrations_dir).exists() {
        return Err(format!("migrations directory not found: {migrations_dir}").into());
    }

    let migrator = ruprizzle_migrate::Migrator::new(migrations_dir);
    let report = migrator.apply_all(&pool, accept_data_loss).await?;

    if report.applied.is_empty() {
        println!("No pending migrations.");
    } else {
        for id in &report.applied {
            println!("Applied {id}");
        }
        println!("Done in {:?}", report.duration);
    }

    Ok(())
}

async fn migrate_status(
    schema_path: &str,
    migrations_dir: &str,
) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    validate(schema_path)?;

    let url = resolve_database_url(schema_path)?;
    let pool = connect(&url).await?;

    let migrator = ruprizzle_migrate::Migrator::new(migrations_dir);
    let status = migrator.status(&pool).await?;

    println!("Applied ({}):", status.applied.len());
    for id in &status.applied {
        println!("  {id}");
    }

    if status.pending.is_empty() {
        println!("No pending migrations.");
    } else {
        println!("Pending ({}):", status.pending.len());
        for id in &status.pending {
            println!("  {id}");
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::CommandFactory;

    #[test]
    fn cli_definition_is_valid() {
        // Catches conflicting flags, bad defaults, and duplicate names at test
        // time rather than on a user's first run.
        Cli::command().debug_assert();
    }

    #[test]
    fn dev_and_deploy_are_separate_subcommands() {
        // The guard from ImplPlan08: `migrate deploy` must not accept the
        // destructive flags that `migrate dev` does, so habit cannot carry a
        // dangerous invocation into production.
        assert!(Cli::try_parse_from(["ruprizzle", "migrate", "dev", "--accept-data-loss"]).is_ok());
        assert!(
            Cli::try_parse_from(["ruprizzle", "migrate", "deploy", "--accept-data-loss"]).is_err()
        );
    }

    #[test]
    fn schema_path_defaults_and_can_be_overridden() {
        let cli = Cli::try_parse_from(["ruprizzle", "validate"]).unwrap();
        assert_eq!(cli.schema, "schema.ruprizzle");

        let cli =
            Cli::try_parse_from(["ruprizzle", "--schema", "db/app.ruprizzle", "validate"]).unwrap();
        assert_eq!(cli.schema, "db/app.ruprizzle");
    }
}
