[package]
name        = "ruprizzle-dialect"
description = "SQL dialect abstraction for the ruprizzle ORM"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true
homepage.workspace     = true
readme                 = "README.md"
documentation          = "https://docs.rs/ruprizzle-dialect"
keywords    = ["orm", "sql", "database", "postgres", "sqlite"]
categories  = ["database"]

[dependencies]
ruprizzle-core = { workspace = true }
thiserror      = { workspace = true }

[dev-dependencies]
ruprizzle-parser = { workspace = true }
