[package]
name        = "ruprizzle-dialect"
description = "SQL dialect abstraction for the ruprizzle ORM"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true
keywords    = ["orm", "sql", "database"]
categories  = ["database"]

[dependencies]
ruprizzle-core = { workspace = true }
thiserror      = { workspace = true }

