//! Turn a list of [`Change`]s into ordered, executable [`Stmt`]s.

use std::collections::{HashMap, HashSet};

use ruprizzle_core::ir::{Field, FieldKind, Model, ScalarType, Schema};
use ruprizzle_core::names::{FieldName, ModelName};
use ruprizzle_dialect::{DbDialect, Stmt};

use crate::change::Change;
use crate::diff::diff;

/// Plans a migration from `prev` to `next` for the given dialect.
///
/// Returns the ordered list of statements to execute.  Destructive statements are
/// tagged by the dialect; this function does not second-guess the dialect.
#[must_use]
pub fn plan(
    prev: &Schema,
    next: &Schema,
    dialect: &dyn DbDialect,
    changes: &[Change],
) -> Vec<Stmt> {
    Planner::new(prev, next, dialect, changes, false).plan()
}

/// Generates the SQL text for the `up.sql` of a migration from `prev` to `next`.
#[must_use]
pub fn up_sql(prev: &Schema, next: &Schema, dialect: &dyn DbDialect) -> String {
    let changes = diff(prev, next);
    let stmts = plan(prev, next, dialect, &changes);
    render_sql(&stmts)
}

/// Generates the SQL text for the `down.sql` of a migration from `prev` to `next`.
///
/// The down migration is produced by diffing in reverse (`next` -> `prev`) and
/// annotated with honest notes about any data that cannot be restored.
#[must_use]
pub fn down_sql(prev: &Schema, next: &Schema, dialect: &dyn DbDialect) -> String {
    let changes = diff(next, prev);
    let mut irreversible = changes
        .iter()
        .filter(|c| c.is_destructive())
        .map(Change::description)
        .peekable();

    let stmts = Planner::new(next, prev, dialect, &changes, true).plan();
    let mut lines = Vec::new();

    lines.push("-- Down migration generated by ruprizzle.".to_string());
    lines.push(
        "-- It restores the schema but cannot restore data that was removed by the up migration."
            .to_string(),
    );

    if irreversible.peek().is_some() {
        lines.push(
            "-- The following up-migration changes are not reversible with their data:".to_string(),
        );
        for note in irreversible {
            lines.push(format!("--   - {note}"));
        }
    }

    lines.push(String::new());

    for stmt in stmts {
        if stmt.destructive {
            lines.push(format!(
                "-- IRREVERSIBLE: {}",
                stmt.sql.trim().trim_end_matches(';')
            ));
        }
        lines.push(stmt.sql.clone());
    }

    lines.join("\n")
}

fn render_sql(stmts: &[Stmt]) -> String {
    stmts
        .iter()
        .map(|s| s.sql.clone())
        .collect::<Vec<_>>()
        .join("\n")
}

struct Planner<'a> {
    prev: &'a Schema,
    next: &'a Schema,
    dialect: &'a dyn DbDialect,
    changes: &'a [Change],
    down: bool,
}

impl<'a> Planner<'a> {
    fn new(
        prev: &'a Schema,
        next: &'a Schema,
        dialect: &'a dyn DbDialect,
        changes: &'a [Change],
        down: bool,
    ) -> Self {
        Self {
            prev,
            next,
            dialect,
            changes,
            down,
        }
    }

    fn plan(&self) -> Vec<Stmt> {
        let mut stmts = Vec::new();
        let needs_defer = self.needs_defer();

        if needs_defer {
            stmts.extend(self.defer_preamble());
        }

        stmts.extend(self.enums_to_create());
        stmts.extend(self.enum_variants_to_add());
        stmts.extend(self.models_to_create());
        stmts.extend(self.columns_to_add());
        stmts.extend(self.columns_to_rename());
        stmts.extend(self.columns_to_alter());
        stmts.extend(self.uniques_to_add());
        stmts.extend(self.indexes_to_create());
        stmts.extend(self.foreign_keys_to_add());
        stmts.extend(self.foreign_keys_to_drop());
        stmts.extend(self.indexes_to_drop());
        stmts.extend(self.uniques_to_drop());
        stmts.extend(self.columns_to_drop());
        stmts.extend(self.models_to_drop());
        stmts.extend(self.enum_variants_to_drop());
        stmts.extend(self.enums_to_drop());

        if needs_defer {
            stmts.extend(self.defer_postamble());
        }

        stmts
    }

    fn filter(&self, f: impl Fn(&Change) -> bool) -> impl Iterator<Item = &Change> {
        self.changes.iter().filter(move |c| f(c))
    }

    fn model(&self, name: &ModelName) -> &Model {
        self.next
            .models
            .get(name)
            .expect("model referenced by change must exist in target schema")
    }

    fn enums_to_create(&self) -> Vec<Stmt> {
        self.filter(|c| matches!(c, Change::CreateEnum(_)))
            .flat_map(|c| match c {
                Change::CreateEnum(e) => self.dialect.create_enum(e),
                _ => Vec::new(),
            })
            .collect()
    }

    fn enums_to_drop(&self) -> Vec<Stmt> {
        self.filter(|c| matches!(c, Change::DropEnum(_, _)))
            .flat_map(|c| match c {
                Change::DropEnum(_, db_name) => {
                    if self.dialect.capabilities().native_enums {
                        vec![
                            Stmt::new(format!(
                                "DROP TYPE IF EXISTS {};",
                                self.dialect.quote_ident(db_name)
                            ))
                            .destructive(),
                        ]
                    } else {
                        Vec::new()
                    }
                }
                _ => Vec::new(),
            })
            .collect()
    }

    fn enum_variants_to_add(&self) -> Vec<Stmt> {
        self.filter(|c| matches!(c, Change::AddEnumVariant { .. }))
            .flat_map(|c| match c {
                Change::AddEnumVariant { enum_, variant } => {
                    let e = self.next.enums.get(enum_).expect("enum must exist");
                    self.dialect.alter_enum_add_variant(e, variant)
                }
                _ => Vec::new(),
            })
            .collect()
    }

    fn enum_variants_to_drop(&self) -> Vec<Stmt> {
        // Dropping enum variants is not directly supported by most SQL dialects;
        // the statement is left as a comment so the migration is not silently wrong.
        self.filter(|c| matches!(c, Change::DropEnumVariant { .. }))
            .map(|c| match c {
                Change::DropEnumVariant { enum_, variant } => Stmt::new(format!(
                    "-- IRREVERSIBLE-PRONE: DROP ENUM VARIANT {enum_}.{variant}"
                )),
                _ => Stmt::new(String::new()),
            })
            .collect()
    }

    fn models_to_create(&self) -> Vec<Stmt> {
        let mut to_create: Vec<&Model> = self
            .filter(|c| matches!(c, Change::CreateModel(_)))
            .filter_map(|c| match c {
                Change::CreateModel(m) => Some(m),
                _ => None,
            })
            .collect();

        // Sort new models so a model is created after all tables it references.
        to_create.sort_by(|a, b| model_dependency_order(self.next, a, b));

        if self.dialect.capabilities().add_fk_after_create {
            // PostgreSQL: create tables without foreign keys, then add them in a
            // second pass so dependency ordering is respected.
            let mut stmts = Vec::new();
            for m in &to_create {
                stmts.extend(self.dialect.create_table(self.next, m));
            }
            stmts
        } else {
            // SQLite: foreign keys must be embedded in CREATE TABLE.
            to_create
                .into_iter()
                .flat_map(|m| ruprizzle_dialect::full_create_table(self.dialect, self.next, m))
                .collect()
        }
    }

    fn models_to_drop(&self) -> Vec<Stmt> {
        let mut to_drop: Vec<&str> = self
            .filter(|c| matches!(c, Change::DropModel(_, _)))
            .filter_map(|c| match c {
                Change::DropModel(_, table) => Some(table.as_str()),
                _ => None,
            })
            .collect();

        // Drop in reverse dependency order: a referencing table is dropped before
        // the table it references.
        to_drop.sort_by(|a, b| table_dependency_order(self.prev, a, b));

        let needs_cascade = self.down && self.dialect.name() == "postgres";
        let cycle_tables = if needs_cascade {
            cycle_table_names(self.prev)
        } else {
            HashSet::new()
        };

        to_drop
            .into_iter()
            .flat_map(|table| {
                let mut stmts = self.dialect.drop_table(table);
                if needs_cascade && cycle_tables.contains(table) {
                    for stmt in &mut stmts {
                        stmt.sql = format!(
                            "{} CASCADE;",
                            stmt.sql.trim_end().trim_end_matches(';').trim_end()
                        );
                    }
                }
                stmts
            })
            .collect()
    }

    fn columns_to_add(&self) -> Vec<Stmt> {
        self.filter(|c| matches!(c, Change::AddColumn { .. }))
            .flat_map(|c| match c {
                Change::AddColumn { model, field } => {
                    let m = self.model(model);
                    self.add_column_with_backfill(m, field)
                }
                _ => Vec::new(),
            })
            .collect()
    }

    fn add_column_with_backfill(&self, m: &Model, field: &Field) -> Vec<Stmt> {
        // A NOT NULL column with no default cannot be added to a table that may
        // already contain rows.  Emit a nullable add, an editable backfill block,
        // then a NOT NULL alter so the user can fill in the middle.
        if !field.optional && field.default.is_none() {
            let mut nullable = field.clone();
            nullable.optional = true;

            let mut stmts = self.dialect.add_column(self.next, m, &nullable);

            let table = self.dialect.quote_ident(&m.table);
            let col = self.dialect.quote_ident(&field.column);
            stmts.push(Stmt::new(format!(
                "-- ▼▼▼ RUPRIZZLE:BACKFILL — edit this block (preserved on regeneration) ▼▼▼\n\
                 -- Column {table}.{col} is NOT NULL with no default and the table may have rows.\n\
                 -- Provide a backfill, then the NOT NULL constraint below will succeed.\n\
                 -- UPDATE {table} SET {col} = <expr> WHERE {col} IS NULL;\n\
                 -- ▲▲▲ RUPRIZZLE:BACKFILL ▲▲▲"
            )));

            stmts.extend(ruprizzle_dialect::full_alter_column(
                self.dialect,
                self.next,
                m,
                &nullable,
                field,
            ));

            return stmts;
        }

        self.dialect.add_column(self.next, m, field)
    }

    fn columns_to_drop(&self) -> Vec<Stmt> {
        self.filter(|c| matches!(c, Change::DropColumn { .. }))
            .flat_map(|c| match c {
                Change::DropColumn { model, column } => {
                    let m = self.model(model);
                    self.dialect.drop_column(&m.table, column)
                }
                _ => Vec::new(),
            })
            .collect()
    }

    fn columns_to_rename(&self) -> Vec<Stmt> {
        self.filter(|c| matches!(c, Change::RenameColumn { .. }))
            .flat_map(|c| match c {
                Change::RenameColumn {
                    model,
                    from,
                    to,
                    from_column,
                    to_column,
                } => {
                    let m = self.model(model);
                    let to_field = m
                        .fields
                        .get(to)
                        .cloned()
                        .unwrap_or_else(|| fallback_field(to, to_column));
                    let mut from_field = to_field.clone();
                    from_field.name = from.clone();
                    from_field.column = from_column.clone();

                    if self.dialect.capabilities().alter_column_type {
                        self.dialect
                            .alter_column(self.next, m, &from_field, &to_field)
                    } else {
                        ruprizzle_dialect::full_alter_column(
                            self.dialect,
                            self.next,
                            m,
                            &from_field,
                            &to_field,
                        )
                    }
                }
                _ => Vec::new(),
            })
            .collect()
    }

    fn columns_to_alter(&self) -> Vec<Stmt> {
        self.filter(|c| matches!(c, Change::AlterColumn { .. }))
            .flat_map(|c| match c {
                Change::AlterColumn {
                    model, from, to, ..
                } => {
                    let m = self.model(model);
                    ruprizzle_dialect::full_alter_column(self.dialect, self.next, m, from, to)
                }
                _ => Vec::new(),
            })
            .collect()
    }

    fn indexes_to_create(&self) -> Vec<Stmt> {
        self.filter(|c| matches!(c, Change::CreateIndex(_, _)))
            .flat_map(|c| match c {
                Change::CreateIndex(model, ix) => {
                    let m = self.model(model);
                    self.dialect.create_index(m, ix)
                }
                _ => Vec::new(),
            })
            .collect()
    }

    fn indexes_to_drop(&self) -> Vec<Stmt> {
        self.filter(|c| matches!(c, Change::DropIndex(_, _)))
            .flat_map(|c| match c {
                Change::DropIndex(model, name) => {
                    let m = self.model(model);
                    self.dialect.drop_index(&m.table, name)
                }
                _ => Vec::new(),
            })
            .collect()
    }

    fn uniques_to_add(&self) -> Vec<Stmt> {
        self.filter(|c| matches!(c, Change::AddUnique(_, _)))
            .flat_map(|c| match c {
                Change::AddUnique(model, uq) => {
                    let m = self.model(model);
                    self.dialect.add_unique(m, uq)
                }
                _ => Vec::new(),
            })
            .collect()
    }

    fn uniques_to_drop(&self) -> Vec<Stmt> {
        self.filter(|c| matches!(c, Change::DropUnique(_, _)))
            .flat_map(|c| match c {
                Change::DropUnique(model, name) => {
                    let m = self.model(model);
                    self.dialect.drop_unique(&m.table, name)
                }
                _ => Vec::new(),
            })
            .collect()
    }

    fn foreign_keys_to_add(&self) -> Vec<Stmt> {
        if !self.dialect.capabilities().add_fk_after_create {
            return Vec::new();
        }
        self.filter(|c| matches!(c, Change::AddForeignKey(_, _)))
            .flat_map(|c| match c {
                Change::AddForeignKey(model, r) => {
                    let m = self.model(model);
                    self.dialect.add_foreign_key(m, r)
                }
                _ => Vec::new(),
            })
            .collect()
    }

    fn foreign_keys_to_drop(&self) -> Vec<Stmt> {
        self.filter(|c| matches!(c, Change::DropForeignKey(_, _)))
            .flat_map(|c| match c {
                Change::DropForeignKey(model, r) => {
                    let m = self.model(model);
                    self.dialect.drop_foreign_key(m, r)
                }
                _ => Vec::new(),
            })
            .collect()
    }
}

fn model_dependency_order(schema: &Schema, a: &Model, b: &Model) -> std::cmp::Ordering {
    let a_refs_b = schema
        .relations
        .iter()
        .any(|r| r.owner == a.name && r.target == b.name);
    let b_refs_a = schema
        .relations
        .iter()
        .any(|r| r.owner == b.name && r.target == a.name);

    if a_refs_b && !b_refs_a {
        // a references b, so a must come after b.
        std::cmp::Ordering::Greater
    } else if b_refs_a && !a_refs_b {
        std::cmp::Ordering::Less
    } else {
        a.name.cmp(&b.name)
    }
}

fn table_dependency_order(schema: &Schema, a: &str, b: &str) -> std::cmp::Ordering {
    let a_model = schema.models.values().find(|m| m.table == a);
    let b_model = schema.models.values().find(|m| m.table == b);

    let a_refs_b = a_model.zip(b_model).map_or(false, |(ma, mb)| {
        schema
            .relations
            .iter()
            .any(|r| r.owner == ma.name && r.target == mb.name)
    });
    let b_refs_a = a_model.zip(b_model).map_or(false, |(ma, mb)| {
        schema
            .relations
            .iter()
            .any(|r| r.owner == mb.name && r.target == ma.name)
    });

    if a_refs_b && !b_refs_a {
        // a references b, so a must be dropped before b.
        std::cmp::Ordering::Less
    } else if b_refs_a && !a_refs_b {
        std::cmp::Ordering::Greater
    } else {
        a.cmp(b)
    }
}

fn fallback_field(name: &FieldName, column: &str) -> Field {
    Field {
        name: name.clone(),
        column: column.to_owned(),
        kind: FieldKind::Scalar(ScalarType::String),
        optional: true,
        default: None,
        attrs: Default::default(),
        docs: None,
        span: Default::default(),
    }
}

// ---------------------------------------------------------------------------
// Foreign-key cycle handling.
// ---------------------------------------------------------------------------

/// Models and relation names that participate in a foreign-key cycle.
struct CycleInfo {
    /// Models in a strongly connected component of the FK graph.
    models: HashSet<ModelName>,
    /// Relations whose owner and target are in the same SCC.
    relations: HashSet<String>,
    /// For each model, the field/column names involved in a cycle relation.
    fields: HashMap<ModelName, HashSet<String>>,
}

/// Builds a directed graph from model to the models it references.
fn fk_graph(schema: &Schema) -> HashMap<ModelName, Vec<ModelName>> {
    let mut graph = HashMap::new();
    for r in &schema.relations {
        graph
            .entry(r.owner.clone())
            .or_insert_with(Vec::new)
            .push(r.target.clone());
    }
    // Ensure every model appears in the graph, even if isolated.
    for name in schema.models.keys() {
        graph.entry(name.clone()).or_insert_with(Vec::new);
    }
    graph
}

/// Computes the strongly connected components of the FK graph and returns the
/// subset that forms a cycle (size > 1 or a self-loop).
fn fk_cycles(schema: &Schema) -> Vec<HashSet<ModelName>> {
    let graph = fk_graph(schema);
    let sccs = tarjan_scc(&graph);

    let mut cycles = Vec::new();
    for scc in sccs {
        if scc.len() > 1 {
            cycles.push(scc);
        } else {
            let model = scc.iter().next().cloned().unwrap();
            if graph
                .get(&model)
                .is_some_and(|targets| targets.contains(&model))
            {
                cycles.push(scc);
            }
        }
    }
    cycles
}

/// Tarjan's strongly connected components algorithm.
fn tarjan_scc(graph: &HashMap<ModelName, Vec<ModelName>>) -> Vec<HashSet<ModelName>> {
    let mut index = 0usize;
    let mut stack: Vec<ModelName> = Vec::new();
    let mut on_stack: HashSet<ModelName> = HashSet::new();
    let mut indices: HashMap<ModelName, usize> = HashMap::new();
    let mut lowlinks: HashMap<ModelName, usize> = HashMap::new();
    let mut sccs: Vec<HashSet<ModelName>> = Vec::new();

    for v in graph.keys().collect::<Vec<_>>() {
        if !indices.contains_key(v) {
            strongconnect(
                v,
                graph,
                &mut index,
                &mut stack,
                &mut on_stack,
                &mut indices,
                &mut lowlinks,
                &mut sccs,
            );
        }
    }

    sccs
}

#[allow(clippy::too_many_arguments)]
fn strongconnect(
    v: &ModelName,
    graph: &HashMap<ModelName, Vec<ModelName>>,
    index: &mut usize,
    stack: &mut Vec<ModelName>,
    on_stack: &mut HashSet<ModelName>,
    indices: &mut HashMap<ModelName, usize>,
    lowlinks: &mut HashMap<ModelName, usize>,
    sccs: &mut Vec<HashSet<ModelName>>,
) {
    indices.insert(v.clone(), *index);
    lowlinks.insert(v.clone(), *index);
    *index += 1;
    stack.push(v.clone());
    on_stack.insert(v.clone());

    for w in graph.get(v).unwrap_or(&Vec::new()) {
        if !indices.contains_key(w) {
            strongconnect(w, graph, index, stack, on_stack, indices, lowlinks, sccs);
            let low_v = lowlinks[v];
            let low_w = lowlinks[w];
            lowlinks.insert(v.clone(), low_v.min(low_w));
        } else if on_stack.contains(w) {
            let low_v = lowlinks[v];
            let idx_w = indices[w];
            lowlinks.insert(v.clone(), low_v.min(idx_w));
        }
    }

    if lowlinks[v] == indices[v] {
        let mut scc = HashSet::new();
        loop {
            let w = stack.pop().unwrap();
            on_stack.remove(&w);
            let done = &w == v;
            scc.insert(w);
            if done {
                break;
            }
        }
        sccs.push(scc);
    }
}

/// Detects the foreign-key cycles in a schema and records which fields/columns
/// are involved so the planner can tell when a change needs deferred checks.
fn cycle_table_names(schema: &Schema) -> HashSet<String> {
    let cycle_info = detect_cycles(schema);
    schema
        .models
        .values()
        .filter(|m| cycle_info.models.contains(&m.name))
        .map(|m| m.table.clone())
        .collect()
}

fn detect_cycles(schema: &Schema) -> CycleInfo {
    let cycles = fk_cycles(schema);
    let mut model_to_scc: HashMap<ModelName, usize> = HashMap::new();
    let mut models = HashSet::new();
    for (idx, scc) in cycles.iter().enumerate() {
        for model in scc {
            model_to_scc.insert(model.clone(), idx);
            models.insert(model.clone());
        }
    }

    let mut relations = HashSet::new();
    let mut fields: HashMap<ModelName, HashSet<String>> = HashMap::new();
    for r in &schema.relations {
        if let (Some(&owner_scc), Some(&target_scc)) =
            (model_to_scc.get(&r.owner), model_to_scc.get(&r.target))
        {
            if owner_scc == target_scc {
                relations.insert(r.name.clone());
                fields
                    .entry(r.owner.clone())
                    .or_default()
                    .insert(r.owner_field.to_string());
                for col in &r.owner_cols {
                    fields
                        .entry(r.owner.clone())
                        .or_default()
                        .insert(col.clone());
                }
            }
        }
    }

    CycleInfo {
        models,
        relations,
        fields,
    }
}

impl Planner<'_> {
    /// Whether this migration touches a foreign-key cycle and needs a preamble
    /// to defer or disable foreign key enforcement.
    fn needs_defer(&self) -> bool {
        // Down migrations on Postgres are handled by adding `CASCADE` to the
        // `DROP TABLE` statements for tables in a cycle.
        if self.down && self.dialect.name() == "postgres" {
            return false;
        }

        if !self.dialect.capabilities().deferrable_fks && self.dialect.name() != "mysql" {
            return false;
        }

        let cycle_schema = if self.down { self.prev } else { self.next };
        let cycle_info = detect_cycles(cycle_schema);

        if cycle_info.models.is_empty() {
            return false;
        }

        self.affects_cycle(&cycle_info)
    }

    /// Returns the statement(s) that begin a migration which must defer foreign
    /// key checks until the end of the transaction (up) or disable them (down).
    fn defer_preamble(&self) -> Vec<Stmt> {
        if self.down {
            self.down_preamble()
        } else {
            self.up_preamble()
        }
    }

    fn up_preamble(&self) -> Vec<Stmt> {
        match self.dialect.name() {
            "postgres" => vec![Stmt::new("SET CONSTRAINTS ALL DEFERRED;")],
            "sqlite" => vec![Stmt::new("PRAGMA defer_foreign_keys = ON;")],
            "mysql" => vec![Stmt::new("SET FOREIGN_KEY_CHECKS = 0;")],
            _ => Vec::new(),
        }
    }

    fn down_preamble(&self) -> Vec<Stmt> {
        match self.dialect.name() {
            "sqlite" => {
                vec![Stmt::new("PRAGMA foreign_keys = OFF;").non_transactional()]
            }
            "mysql" => vec![Stmt::new("SET FOREIGN_KEY_CHECKS = 0;")],
            _ => Vec::new(),
        }
    }

    /// Returns the statement(s) that re-enable foreign key checks before commit.
    fn defer_postamble(&self) -> Vec<Stmt> {
        if self.down {
            self.down_postamble()
        } else {
            self.up_postamble()
        }
    }

    fn up_postamble(&self) -> Vec<Stmt> {
        match self.dialect.name() {
            "postgres" => vec![Stmt::new("SET CONSTRAINTS ALL IMMEDIATE;")],
            "sqlite" => vec![Stmt::new("PRAGMA defer_foreign_keys = OFF;")],
            "mysql" => vec![Stmt::new("SET FOREIGN_KEY_CHECKS = 1;")],
            _ => Vec::new(),
        }
    }

    fn down_postamble(&self) -> Vec<Stmt> {
        match self.dialect.name() {
            "sqlite" => vec![
                Stmt::new("PRAGMA foreign_key_check;").non_transactional(),
                Stmt::new("PRAGMA foreign_keys = ON;").non_transactional(),
            ],
            "mysql" => vec![Stmt::new("SET FOREIGN_KEY_CHECKS = 1;")],
            _ => Vec::new(),
        }
    }

    /// Whether any of the planned changes touches the detected cycle.
    fn affects_cycle(&self, cycle: &CycleInfo) -> bool {
        let cycle_fields = |model: &ModelName, field_name: &FieldName, column: &str| {
            cycle
                .fields
                .get(model)
                .is_some_and(|set| set.contains(field_name.as_str()) || set.contains(column))
        };

        for change in self.changes {
            match change {
                Change::CreateModel(m)
                    if cycle.models.contains(&m.name) => {
                        return true;
                    }
                Change::DropModel(m, _)
                    if cycle.models.contains(m) => {
                        return true;
                    }
                Change::RenameModel { from, to, .. }
                    if (cycle.models.contains(from) || cycle.models.contains(to)) => {
                        return true;
                    }
                Change::AddColumn { model, field }
                    if cycle.models.contains(model)
                        && cycle_fields(model, &field.name, &field.column)
                    => {
                        return true;
                    }
                Change::AlterColumn { model, from, to, .. }
                    if cycle.models.contains(model)
                        && (cycle_fields(model, &from.name, &from.column)
                            || cycle_fields(model, &to.name, &to.column))
                    => {
                        return true;
                    }
                Change::DropColumn { model, column }
                    if cycle.models.contains(model)
                        && cycle
                            .fields
                            .get(model)
                            .is_some_and(|set| set.contains(column))
                        => {
                            return true;
                        }
                Change::RenameColumn {
                    model,
                    from,
                    to,
                    from_column,
                    to_column,
                }
                    if cycle.models.contains(model)
                        && (cycle_fields(model, from, from_column)
                            || cycle_fields(model, to, to_column))
                    => {
                        return true;
                    }
                Change::AddForeignKey(_, r) | Change::DropForeignKey(_, r)
                    if cycle.relations.contains(&r.name) => {
                        return true;
                    }
                _ => {}
            }
        }

        false
    }
}
