[package]
name        = "ruprizzle-macros"
description = "Proc-macro support for the ruprizzle ORM"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true
homepage.workspace     = true
readme                 = "README.md"
documentation          = "https://docs.rs/ruprizzle-macros"
keywords    = ["orm", "sql", "database", "macros", "proc-macro"]
categories  = ["database"]

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "3"
proc-macro2    = { workspace = true }
quote          = { workspace = true }
syn            = { workspace = true }
